//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.10 at 12:46:59 AM EST 
//


package xml.us.patent.grant.vST32_024;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "b110",
    "b122US",
    "b130",
    "b140",
    "b190"
})
@XmlRootElement(name = "B100")
public class B100 {

    @XmlAttribute(name = "INID")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String inid;
    @XmlElement(name = "B110", required = true)
    protected B110 b110;
    @XmlElement(name = "B122US")
    protected B122US b122US;
    @XmlElement(name = "B130", required = true)
    protected B130 b130;
    @XmlElement(name = "B140", required = true)
    protected B140 b140;
    @XmlElement(name = "B190", required = true)
    protected B190 b190;

    /**
     * Gets the value of the inid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINID() {
        if (inid == null) {
            return "[10]";
        } else {
            return inid;
        }
    }

    /**
     * Sets the value of the inid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINID(String value) {
        this.inid = value;
    }

    /**
     * Gets the value of the b110 property.
     * 
     * @return
     *     possible object is
     *     {@link B110 }
     *     
     */
    public B110 getB110() {
        return b110;
    }

    /**
     * Sets the value of the b110 property.
     * 
     * @param value
     *     allowed object is
     *     {@link B110 }
     *     
     */
    public void setB110(B110 value) {
        this.b110 = value;
    }

    /**
     * Gets the value of the b122US property.
     * 
     * @return
     *     possible object is
     *     {@link B122US }
     *     
     */
    public B122US getB122US() {
        return b122US;
    }

    /**
     * Sets the value of the b122US property.
     * 
     * @param value
     *     allowed object is
     *     {@link B122US }
     *     
     */
    public void setB122US(B122US value) {
        this.b122US = value;
    }

    /**
     * Gets the value of the b130 property.
     * 
     * @return
     *     possible object is
     *     {@link B130 }
     *     
     */
    public B130 getB130() {
        return b130;
    }

    /**
     * Sets the value of the b130 property.
     * 
     * @param value
     *     allowed object is
     *     {@link B130 }
     *     
     */
    public void setB130(B130 value) {
        this.b130 = value;
    }

    /**
     * Gets the value of the b140 property.
     * 
     * @return
     *     possible object is
     *     {@link B140 }
     *     
     */
    public B140 getB140() {
        return b140;
    }

    /**
     * Sets the value of the b140 property.
     * 
     * @param value
     *     allowed object is
     *     {@link B140 }
     *     
     */
    public void setB140(B140 value) {
        this.b140 = value;
    }

    /**
     * Gets the value of the b190 property.
     * 
     * @return
     *     possible object is
     *     {@link B190 }
     *     
     */
    public B190 getB190() {
        return b190;
    }

    /**
     * Sets the value of the b190 property.
     * 
     * @param value
     *     allowed object is
     *     {@link B190 }
     *     
     */
    public void setB190(B190 value) {
        this.b190 = value;
    }

}
