//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.10 at 12:46:59 AM EST 
//


package xml.us.patent.grant.vST32_024;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "b473",
    "b473US",
    "b474",
    "b474US"
})
@XmlRootElement(name = "B472")
public class B472 {

    @XmlElement(name = "B473")
    protected B473 b473;
    @XmlElement(name = "B473US")
    protected B473US b473US;
    @XmlElement(name = "B474")
    protected B474 b474;
    @XmlElement(name = "B474US")
    protected B474US b474US;

    /**
     * Gets the value of the b473 property.
     * 
     * @return
     *     possible object is
     *     {@link B473 }
     *     
     */
    public B473 getB473() {
        return b473;
    }

    /**
     * Sets the value of the b473 property.
     * 
     * @param value
     *     allowed object is
     *     {@link B473 }
     *     
     */
    public void setB473(B473 value) {
        this.b473 = value;
    }

    /**
     * Gets the value of the b473US property.
     * 
     * @return
     *     possible object is
     *     {@link B473US }
     *     
     */
    public B473US getB473US() {
        return b473US;
    }

    /**
     * Sets the value of the b473US property.
     * 
     * @param value
     *     allowed object is
     *     {@link B473US }
     *     
     */
    public void setB473US(B473US value) {
        this.b473US = value;
    }

    /**
     * Gets the value of the b474 property.
     * 
     * @return
     *     possible object is
     *     {@link B474 }
     *     
     */
    public B474 getB474() {
        return b474;
    }

    /**
     * Sets the value of the b474 property.
     * 
     * @param value
     *     allowed object is
     *     {@link B474 }
     *     
     */
    public void setB474(B474 value) {
        this.b474 = value;
    }

    /**
     * Gets the value of the b474US property.
     * 
     * @return
     *     possible object is
     *     {@link B474US }
     *     
     */
    public B474US getB474US() {
        return b474US;
    }

    /**
     * Sets the value of the b474US property.
     * 
     * @param value
     *     allowed object is
     *     {@link B474US }
     *     
     */
    public void setB474US(B474US value) {
        this.b474US = value;
    }

}
