//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.10 at 12:46:59 AM EST 
//


package xml.us.patent.grant.vST32_024;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "b594US",
    "b595",
    "b595US",
    "b596",
    "b597US"
})
@XmlRootElement(name = "B590")
public class B590 {

    @XmlElement(name = "B594US")
    protected B594US b594US;
    @XmlElement(name = "B595")
    protected B595 b595;
    @XmlElement(name = "B595US")
    protected B595US b595US;
    @XmlElement(name = "B596", required = true)
    protected B596 b596;
    @XmlElement(name = "B597US")
    protected B597US b597US;

    /**
     * Gets the value of the b594US property.
     * 
     * @return
     *     possible object is
     *     {@link B594US }
     *     
     */
    public B594US getB594US() {
        return b594US;
    }

    /**
     * Sets the value of the b594US property.
     * 
     * @param value
     *     allowed object is
     *     {@link B594US }
     *     
     */
    public void setB594US(B594US value) {
        this.b594US = value;
    }

    /**
     * Gets the value of the b595 property.
     * 
     * @return
     *     possible object is
     *     {@link B595 }
     *     
     */
    public B595 getB595() {
        return b595;
    }

    /**
     * Sets the value of the b595 property.
     * 
     * @param value
     *     allowed object is
     *     {@link B595 }
     *     
     */
    public void setB595(B595 value) {
        this.b595 = value;
    }

    /**
     * Gets the value of the b595US property.
     * 
     * @return
     *     possible object is
     *     {@link B595US }
     *     
     */
    public B595US getB595US() {
        return b595US;
    }

    /**
     * Sets the value of the b595US property.
     * 
     * @param value
     *     allowed object is
     *     {@link B595US }
     *     
     */
    public void setB595US(B595US value) {
        this.b595US = value;
    }

    /**
     * Gets the value of the b596 property.
     * 
     * @return
     *     possible object is
     *     {@link B596 }
     *     
     */
    public B596 getB596() {
        return b596;
    }

    /**
     * Sets the value of the b596 property.
     * 
     * @param value
     *     allowed object is
     *     {@link B596 }
     *     
     */
    public void setB596(B596 value) {
        this.b596 = value;
    }

    /**
     * Gets the value of the b597US property.
     * 
     * @return
     *     possible object is
     *     {@link B597US }
     *     
     */
    public B597US getB597US() {
        return b597US;
    }

    /**
     * Sets the value of the b597US property.
     * 
     * @param value
     *     allowed object is
     *     {@link B597US }
     *     
     */
    public void setB597US(B597US value) {
        this.b597US = value;
    }

}
