//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.10 at 12:46:59 AM EST 
//


package xml.us.patent.grant.vST32_024;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "b860",
    "b870"
})
@XmlRootElement(name = "B800")
public class B800 {

    @XmlElement(name = "B860", required = true)
    protected B860 b860;
    @XmlElement(name = "B870")
    protected B870 b870;

    /**
     * Gets the value of the b860 property.
     * 
     * @return
     *     possible object is
     *     {@link B860 }
     *     
     */
    public B860 getB860() {
        return b860;
    }

    /**
     * Sets the value of the b860 property.
     * 
     * @param value
     *     allowed object is
     *     {@link B860 }
     *     
     */
    public void setB860(B860 value) {
        this.b860 = value;
    }

    /**
     * Gets the value of the b870 property.
     * 
     * @return
     *     possible object is
     *     {@link B870 }
     *     
     */
    public B870 getB870() {
        return b870;
    }

    /**
     * Sets the value of the b870 property.
     * 
     * @param value
     *     allowed object is
     *     {@link B870 }
     *     
     */
    public void setB870(B870 value) {
        this.b870 = value;
    }

}
