//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.10 at 12:46:59 AM EST 
//


package xml.us.patent.grant.vST32_024;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "b831",
    "b832",
    "b833"
})
@XmlRootElement(name = "B830")
public class B830 {

    @XmlElement(name = "B831", required = true)
    protected B831 b831;
    @XmlElement(name = "B832")
    protected B832 b832;
    @XmlElement(name = "B833")
    protected B833 b833;

    /**
     * Gets the value of the b831 property.
     * 
     * @return
     *     possible object is
     *     {@link B831 }
     *     
     */
    public B831 getB831() {
        return b831;
    }

    /**
     * Sets the value of the b831 property.
     * 
     * @param value
     *     allowed object is
     *     {@link B831 }
     *     
     */
    public void setB831(B831 value) {
        this.b831 = value;
    }

    /**
     * Gets the value of the b832 property.
     * 
     * @return
     *     possible object is
     *     {@link B832 }
     *     
     */
    public B832 getB832() {
        return b832;
    }

    /**
     * Sets the value of the b832 property.
     * 
     * @param value
     *     allowed object is
     *     {@link B832 }
     *     
     */
    public void setB832(B832 value) {
        this.b832 = value;
    }

    /**
     * Gets the value of the b833 property.
     * 
     * @return
     *     possible object is
     *     {@link B833 }
     *     
     */
    public B833 getB833() {
        return b833;
    }

    /**
     * Sets the value of the b833 property.
     * 
     * @param value
     *     allowed object is
     *     {@link B833 }
     *     
     */
    public void setB833(B833 value) {
        this.b833 = value;
    }

}
