//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.10 at 12:46:59 AM EST 
//


package xml.us.patent.grant.vST32_024;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "stext"
})
@XmlRootElement(name = "ELE")
public class ELE {

    @XmlAttribute(name = "ID", required = true)
    @XmlIDREF
    protected Object id;
    @XmlElement(name = "STEXT", required = true)
    protected STEXT stext;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setID(Object value) {
        this.id = value;
    }

    /**
     * Gets the value of the stext property.
     * 
     * @return
     *     possible object is
     *     {@link STEXT }
     *     
     */
    public STEXT getSTEXT() {
        return stext;
    }

    /**
     * Sets the value of the stext property.
     * 
     * @param value
     *     allowed object is
     *     {@link STEXT }
     *     
     */
    public void setSTEXT(STEXT value) {
        this.stext = value;
    }

}
