//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.10 at 12:46:59 AM EST 
//


package xml.us.patent.grant.vST32_024;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "s130",
    "s160",
    "s170"
})
@XmlRootElement(name = "S100")
public class S100 {

    @XmlElement(name = "S130")
    protected S130 s130;
    @XmlElement(name = "S160", required = true)
    protected S160 s160;
    @XmlElement(name = "S170")
    protected S170 s170;

    /**
     * Gets the value of the s130 property.
     * 
     * @return
     *     possible object is
     *     {@link S130 }
     *     
     */
    public S130 getS130() {
        return s130;
    }

    /**
     * Sets the value of the s130 property.
     * 
     * @param value
     *     allowed object is
     *     {@link S130 }
     *     
     */
    public void setS130(S130 value) {
        this.s130 = value;
    }

    /**
     * Gets the value of the s160 property.
     * 
     * @return
     *     possible object is
     *     {@link S160 }
     *     
     */
    public S160 getS160() {
        return s160;
    }

    /**
     * Sets the value of the s160 property.
     * 
     * @param value
     *     allowed object is
     *     {@link S160 }
     *     
     */
    public void setS160(S160 value) {
        this.s160 = value;
    }

    /**
     * Gets the value of the s170 property.
     * 
     * @return
     *     possible object is
     *     {@link S170 }
     *     
     */
    public S170 getS170() {
        return s170;
    }

    /**
     * Sets the value of the s170 property.
     * 
     * @param value
     *     allowed object is
     *     {@link S170 }
     *     
     */
    public void setS170(S170 value) {
        this.s170 = value;
    }

}
