//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.10 at 12:46:59 AM EST 
//


package xml.us.patent.grant.vST32_024;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "s1IXA",
    "s1IXB",
    "s1IXC"
})
@XmlRootElement(name = "S-1-IX")
public class S1IX {

    @XmlElement(name = "S-1-IX-A", required = true)
    protected S1IXA s1IXA;
    @XmlElement(name = "S-1-IX-B", required = true)
    protected S1IXB s1IXB;
    @XmlElement(name = "S-1-IX-C", required = true)
    protected S1IXC s1IXC;

    /**
     * Gets the value of the s1IXA property.
     * 
     * @return
     *     possible object is
     *     {@link S1IXA }
     *     
     */
    public S1IXA getS1IXA() {
        return s1IXA;
    }

    /**
     * Sets the value of the s1IXA property.
     * 
     * @param value
     *     allowed object is
     *     {@link S1IXA }
     *     
     */
    public void setS1IXA(S1IXA value) {
        this.s1IXA = value;
    }

    /**
     * Gets the value of the s1IXB property.
     * 
     * @return
     *     possible object is
     *     {@link S1IXB }
     *     
     */
    public S1IXB getS1IXB() {
        return s1IXB;
    }

    /**
     * Sets the value of the s1IXB property.
     * 
     * @param value
     *     allowed object is
     *     {@link S1IXB }
     *     
     */
    public void setS1IXB(S1IXB value) {
        this.s1IXB = value;
    }

    /**
     * Gets the value of the s1IXC property.
     * 
     * @return
     *     possible object is
     *     {@link S1IXC }
     *     
     */
    public S1IXC getS1IXC() {
        return s1IXC;
    }

    /**
     * Sets the value of the s1IXC property.
     * 
     * @param value
     *     allowed object is
     *     {@link S1IXC }
     *     
     */
    public void setS1IXC(S1IXC value) {
        this.s1IXC = value;
    }

}
