//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.10 at 12:46:59 AM EST 
//


package xml.us.patent.grant.vST32_024;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "s221",
    "s222",
    "s223"
})
@XmlRootElement(name = "S220")
public class S220 {

    @XmlElement(name = "S221")
    protected S221 s221;
    @XmlElement(name = "S222")
    protected S222 s222;
    @XmlElement(name = "S223")
    protected S223 s223;

    /**
     * Gets the value of the s221 property.
     * 
     * @return
     *     possible object is
     *     {@link S221 }
     *     
     */
    public S221 getS221() {
        return s221;
    }

    /**
     * Sets the value of the s221 property.
     * 
     * @param value
     *     allowed object is
     *     {@link S221 }
     *     
     */
    public void setS221(S221 value) {
        this.s221 = value;
    }

    /**
     * Gets the value of the s222 property.
     * 
     * @return
     *     possible object is
     *     {@link S222 }
     *     
     */
    public S222 getS222() {
        return s222;
    }

    /**
     * Sets the value of the s222 property.
     * 
     * @param value
     *     allowed object is
     *     {@link S222 }
     *     
     */
    public void setS222(S222 value) {
        this.s222 = value;
    }

    /**
     * Gets the value of the s223 property.
     * 
     * @return
     *     possible object is
     *     {@link S223 }
     *     
     */
    public S223 getS223() {
        return s223;
    }

    /**
     * Sets the value of the s223 property.
     * 
     * @param value
     *     allowed object is
     *     {@link S223 }
     *     
     */
    public void setS223(S223 value) {
        this.s223 = value;
    }

}
