//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.10 at 12:46:59 AM EST 
//


package xml.us.patent.grant.vST32_024;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "emiOrDELSOrDELEOrINSSOrINSE"
})
@XmlRootElement(name = "SDODR")
public class SDODR {

    @XmlAttribute(name = "ID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    @XmlAttribute(name = "LA")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String la;
    @XmlAttribute(name = "CY")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String cy;
    @XmlAttribute(name = "STATUS")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String status;
    @XmlElements({
        @XmlElement(name = "EMI", type = EMI.class),
        @XmlElement(name = "DEL-S", type = DELS.class),
        @XmlElement(name = "DEL-E", type = DELE.class),
        @XmlElement(name = "INS-S", type = INSS.class),
        @XmlElement(name = "INS-E", type = INSE.class)
    })
    protected List<Object> emiOrDELSOrDELEOrINSSOrINSE;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the la property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLA() {
        return la;
    }

    /**
     * Sets the value of the la property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLA(String value) {
        this.la = value;
    }

    /**
     * Gets the value of the cy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCY() {
        return cy;
    }

    /**
     * Sets the value of the cy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCY(String value) {
        this.cy = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTATUS() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTATUS(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the emiOrDELSOrDELEOrINSSOrINSE property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the emiOrDELSOrDELEOrINSSOrINSE property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEMIOrDELSOrDELEOrINSSOrINSE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EMI }
     * {@link DELS }
     * {@link DELE }
     * {@link INSS }
     * {@link INSE }
     * 
     * 
     */
    public List<Object> getEMIOrDELSOrDELEOrINSSOrINSE() {
        if (emiOrDELSOrDELEOrINSSOrINSE == null) {
            emiOrDELSOrDELEOrINSSOrINSE = new ArrayList<Object>();
        }
        return this.emiOrDELSOrDELEOrINSSOrINSE;
    }

}
