//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.16 at 01:02:44 PM EST 
//


package xml.us.patent.grant.v41;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nameOrPrefixOrLastNameOrOrgnameOrFirstNameOrMiddleNameOrSuffixOrIidOrRoleOrDepartmentOrSynonymOrRegisteredNumberOrAddressbook"
})
@XmlRootElement(name = "searcher")
public class Searcher {

    @XmlElements({
        @XmlElement(name = "name", required = true, type = Name.class),
        @XmlElement(name = "prefix", required = true, type = Prefix.class),
        @XmlElement(name = "last-name", required = true, type = LastName.class),
        @XmlElement(name = "orgname", required = true, type = Orgname.class),
        @XmlElement(name = "first-name", required = true, type = FirstName.class),
        @XmlElement(name = "middle-name", required = true, type = MiddleName.class),
        @XmlElement(name = "suffix", required = true, type = Suffix.class),
        @XmlElement(name = "iid", required = true, type = Iid.class),
        @XmlElement(name = "role", required = true, type = Role.class),
        @XmlElement(name = "department", required = true, type = Department.class),
        @XmlElement(name = "synonym", required = true, type = Synonym.class),
        @XmlElement(name = "registered-number", required = true, type = RegisteredNumber.class),
        @XmlElement(name = "addressbook", required = true, type = Addressbook.class)
    })
    protected List<Object> nameOrPrefixOrLastNameOrOrgnameOrFirstNameOrMiddleNameOrSuffixOrIidOrRoleOrDepartmentOrSynonymOrRegisteredNumberOrAddressbook;

    /**
     * Gets the value of the nameOrPrefixOrLastNameOrOrgnameOrFirstNameOrMiddleNameOrSuffixOrIidOrRoleOrDepartmentOrSynonymOrRegisteredNumberOrAddressbook property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nameOrPrefixOrLastNameOrOrgnameOrFirstNameOrMiddleNameOrSuffixOrIidOrRoleOrDepartmentOrSynonymOrRegisteredNumberOrAddressbook property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNameOrPrefixOrLastNameOrOrgnameOrFirstNameOrMiddleNameOrSuffixOrIidOrRoleOrDepartmentOrSynonymOrRegisteredNumberOrAddressbook().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Name }
     * {@link Prefix }
     * {@link LastName }
     * {@link Orgname }
     * {@link FirstName }
     * {@link MiddleName }
     * {@link Suffix }
     * {@link Iid }
     * {@link Role }
     * {@link Department }
     * {@link Synonym }
     * {@link RegisteredNumber }
     * {@link Addressbook }
     * 
     * 
     */
    public List<Object> getNameOrPrefixOrLastNameOrOrgnameOrFirstNameOrMiddleNameOrSuffixOrIidOrRoleOrDepartmentOrSynonymOrRegisteredNumberOrAddressbook() {
        if (nameOrPrefixOrLastNameOrOrgnameOrFirstNameOrMiddleNameOrSuffixOrIidOrRoleOrDepartmentOrSynonymOrRegisteredNumberOrAddressbook == null) {
            nameOrPrefixOrLastNameOrOrgnameOrFirstNameOrMiddleNameOrSuffixOrIidOrRoleOrDepartmentOrSynonymOrRegisteredNumberOrAddressbook = new ArrayList<Object>();
        }
        return this.nameOrPrefixOrLastNameOrOrgnameOrFirstNameOrMiddleNameOrSuffixOrIidOrRoleOrDepartmentOrSynonymOrRegisteredNumberOrAddressbook;
    }

}
