//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.16 at 12:46:18 PM EST 
//


package xml.us.patent.application.v43;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "mainCpc",
    "furtherCpc"
})
@XmlRootElement(name = "classifications-cpc")
public class ClassificationsCpc {

    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    @XmlElement(name = "main-cpc", required = true)
    protected MainCpc mainCpc;
    @XmlElement(name = "further-cpc")
    protected FurtherCpc furtherCpc;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the mainCpc property.
     * 
     * @return
     *     possible object is
     *     {@link MainCpc }
     *     
     */
    public MainCpc getMainCpc() {
        return mainCpc;
    }

    /**
     * Sets the value of the mainCpc property.
     * 
     * @param value
     *     allowed object is
     *     {@link MainCpc }
     *     
     */
    public void setMainCpc(MainCpc value) {
        this.mainCpc = value;
    }

    /**
     * Gets the value of the furtherCpc property.
     * 
     * @return
     *     possible object is
     *     {@link FurtherCpc }
     *     
     */
    public FurtherCpc getFurtherCpc() {
        return furtherCpc;
    }

    /**
     * Sets the value of the furtherCpc property.
     * 
     * @param value
     *     allowed object is
     *     {@link FurtherCpc }
     *     
     */
    public void setFurtherCpc(FurtherCpc value) {
        this.furtherCpc = value;
    }

}
