//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.16 at 01:04:30 PM EST 
//


package xml.us.patent.grant.v40_041028;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "classificationIpcOrClassificationsIpcrOrClassificationNational"
})
@XmlRootElement(name = "field-of-search")
public class FieldOfSearch {

    @XmlElements({
        @XmlElement(name = "classification-ipc", required = true, type = ClassificationIpc.class),
        @XmlElement(name = "classifications-ipcr", required = true, type = ClassificationsIpcr.class),
        @XmlElement(name = "classification-national", required = true, type = ClassificationNational.class)
    })
    protected List<Object> classificationIpcOrClassificationsIpcrOrClassificationNational;

    /**
     * Gets the value of the classificationIpcOrClassificationsIpcrOrClassificationNational property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the classificationIpcOrClassificationsIpcrOrClassificationNational property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClassificationIpcOrClassificationsIpcrOrClassificationNational().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ClassificationIpc }
     * {@link ClassificationsIpcr }
     * {@link ClassificationNational }
     * 
     * 
     */
    public List<Object> getClassificationIpcOrClassificationsIpcrOrClassificationNational() {
        if (classificationIpcOrClassificationsIpcrOrClassificationNational == null) {
            classificationIpcOrClassificationsIpcrOrClassificationNational = new ArrayList<Object>();
        }
        return this.classificationIpcOrClassificationsIpcrOrClassificationNational;
    }

}
