//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.16 at 12:45:57 PM EST 
//


package xml.us.patent.application.v44;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "documentId",
    "internationalFilingDate"
})
@XmlRootElement(name = "child-doc")
public class ChildDoc {

    @XmlElement(name = "document-id", required = true)
    protected DocumentId documentId;
    @XmlElement(name = "international-filing-date")
    protected InternationalFilingDate internationalFilingDate;

    /**
     * Gets the value of the documentId property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentId }
     *     
     */
    public DocumentId getDocumentId() {
        return documentId;
    }

    /**
     * Sets the value of the documentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentId }
     *     
     */
    public void setDocumentId(DocumentId value) {
        this.documentId = value;
    }

    /**
     * Gets the value of the internationalFilingDate property.
     * 
     * @return
     *     possible object is
     *     {@link InternationalFilingDate }
     *     
     */
    public InternationalFilingDate getInternationalFilingDate() {
        return internationalFilingDate;
    }

    /**
     * Sets the value of the internationalFilingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternationalFilingDate }
     *     
     */
    public void setInternationalFilingDate(InternationalFilingDate value) {
        this.internationalFilingDate = value;
    }

}
