//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.16 at 01:01:40 PM EST 
//


package xml.us.patent.grant.v45;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "internationalFilingDate",
    "internationalRegistrationPublicationDate",
    "internationalRegistrationNumber",
    "internationalRegistrationDate"
})
@XmlRootElement(name = "hague-agreement-data")
public class HagueAgreementData {

    @XmlElement(name = "international-filing-date", required = true)
    protected InternationalFilingDate internationalFilingDate;
    @XmlElement(name = "international-registration-publication-date", required = true)
    protected InternationalRegistrationPublicationDate internationalRegistrationPublicationDate;
    @XmlElement(name = "international-registration-number", required = true)
    protected String internationalRegistrationNumber;
    @XmlElement(name = "international-registration-date", required = true)
    protected InternationalRegistrationDate internationalRegistrationDate;

    /**
     * Gets the value of the internationalFilingDate property.
     * 
     * @return
     *     possible object is
     *     {@link InternationalFilingDate }
     *     
     */
    public InternationalFilingDate getInternationalFilingDate() {
        return internationalFilingDate;
    }

    /**
     * Sets the value of the internationalFilingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternationalFilingDate }
     *     
     */
    public void setInternationalFilingDate(InternationalFilingDate value) {
        this.internationalFilingDate = value;
    }

    /**
     * Gets the value of the internationalRegistrationPublicationDate property.
     * 
     * @return
     *     possible object is
     *     {@link InternationalRegistrationPublicationDate }
     *     
     */
    public InternationalRegistrationPublicationDate getInternationalRegistrationPublicationDate() {
        return internationalRegistrationPublicationDate;
    }

    /**
     * Sets the value of the internationalRegistrationPublicationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternationalRegistrationPublicationDate }
     *     
     */
    public void setInternationalRegistrationPublicationDate(InternationalRegistrationPublicationDate value) {
        this.internationalRegistrationPublicationDate = value;
    }

    /**
     * Gets the value of the internationalRegistrationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternationalRegistrationNumber() {
        return internationalRegistrationNumber;
    }

    /**
     * Sets the value of the internationalRegistrationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternationalRegistrationNumber(String value) {
        this.internationalRegistrationNumber = value;
    }

    /**
     * Gets the value of the internationalRegistrationDate property.
     * 
     * @return
     *     possible object is
     *     {@link InternationalRegistrationDate }
     *     
     */
    public InternationalRegistrationDate getInternationalRegistrationDate() {
        return internationalRegistrationDate;
    }

    /**
     * Sets the value of the internationalRegistrationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternationalRegistrationDate }
     *     
     */
    public void setInternationalRegistrationDate(InternationalRegistrationDate value) {
        this.internationalRegistrationDate = value;
    }

}
