//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.16 at 12:48:42 PM EST 
//


package xml.us.patent.application.v40_040908;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "regionOrCountry"
})
@XmlRootElement(name = "office-of-filing")
public class OfficeOfFiling {

    @XmlElements({
        @XmlElement(name = "region", required = true, type = Region.class),
        @XmlElement(name = "country", required = true, type = Country.class)
    })
    protected List<Object> regionOrCountry;

    /**
     * Gets the value of the regionOrCountry property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the regionOrCountry property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRegionOrCountry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Region }
     * {@link Country }
     * 
     * 
     */
    public List<Object> getRegionOrCountry() {
        if (regionOrCountry == null) {
            regionOrCountry = new ArrayList<Object>();
        }
        return this.regionOrCountry;
    }

}
