//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.10 at 07:08:34 PM EST 
//


package xml.us.patent.application.v16;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "number",
    "depositDate",
    "depositTerm",
    "depository",
    "depositAccessionNumber",
    "depositDescription"
})
@XmlRootElement(name = "biological-deposit")
public class BiologicalDeposit {

    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    @XmlAttribute(name = "st32-name")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String st32Name;
    @XmlElement(required = true)
    protected String number;
    @XmlElement(name = "deposit-date", required = true)
    protected DepositDate depositDate;
    @XmlElement(name = "deposit-term", required = true)
    protected String depositTerm;
    @XmlElement(required = true)
    protected Depository depository;
    @XmlElement(name = "deposit-accession-number", required = true)
    protected DepositAccessionNumber depositAccessionNumber;
    @XmlElement(name = "deposit-description", required = true)
    protected String depositDescription;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the st32Name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSt32Name() {
        if (st32Name == null) {
            return "B830";
        } else {
            return st32Name;
        }
    }

    /**
     * Sets the value of the st32Name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSt32Name(String value) {
        this.st32Name = value;
    }

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumber(String value) {
        this.number = value;
    }

    /**
     * Gets the value of the depositDate property.
     * 
     * @return
     *     possible object is
     *     {@link DepositDate }
     *     
     */
    public DepositDate getDepositDate() {
        return depositDate;
    }

    /**
     * Sets the value of the depositDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DepositDate }
     *     
     */
    public void setDepositDate(DepositDate value) {
        this.depositDate = value;
    }

    /**
     * Gets the value of the depositTerm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepositTerm() {
        return depositTerm;
    }

    /**
     * Sets the value of the depositTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepositTerm(String value) {
        this.depositTerm = value;
    }

    /**
     * Gets the value of the depository property.
     * 
     * @return
     *     possible object is
     *     {@link Depository }
     *     
     */
    public Depository getDepository() {
        return depository;
    }

    /**
     * Sets the value of the depository property.
     * 
     * @param value
     *     allowed object is
     *     {@link Depository }
     *     
     */
    public void setDepository(Depository value) {
        this.depository = value;
    }

    /**
     * Gets the value of the depositAccessionNumber property.
     * 
     * @return
     *     possible object is
     *     {@link DepositAccessionNumber }
     *     
     */
    public DepositAccessionNumber getDepositAccessionNumber() {
        return depositAccessionNumber;
    }

    /**
     * Sets the value of the depositAccessionNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link DepositAccessionNumber }
     *     
     */
    public void setDepositAccessionNumber(DepositAccessionNumber value) {
        this.depositAccessionNumber = value;
    }

    /**
     * Gets the value of the depositDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepositDescription() {
        return depositDescription;
    }

    /**
     * Sets the value of the depositDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepositDescription(String value) {
        this.depositDescription = value;
    }

}
