//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.10 at 07:08:34 PM EST 
//


package xml.us.patent.application.v16;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "classificationUsPrimary",
    "classificationUsSecondary"
})
@XmlRootElement(name = "classification-us")
public class ClassificationUs {

    @XmlAttribute(name = "st32-name")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String st32Name;
    @XmlAttribute(name = "inid-code")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String inidCode;
    @XmlElement(name = "classification-us-primary", required = true)
    protected ClassificationUsPrimary classificationUsPrimary;
    @XmlElement(name = "classification-us-secondary")
    protected List<ClassificationUsSecondary> classificationUsSecondary;

    /**
     * Gets the value of the st32Name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSt32Name() {
        if (st32Name == null) {
            return "B520";
        } else {
            return st32Name;
        }
    }

    /**
     * Sets the value of the st32Name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSt32Name(String value) {
        this.st32Name = value;
    }

    /**
     * Gets the value of the inidCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInidCode() {
        return inidCode;
    }

    /**
     * Sets the value of the inidCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInidCode(String value) {
        this.inidCode = value;
    }

    /**
     * Gets the value of the classificationUsPrimary property.
     * 
     * @return
     *     possible object is
     *     {@link ClassificationUsPrimary }
     *     
     */
    public ClassificationUsPrimary getClassificationUsPrimary() {
        return classificationUsPrimary;
    }

    /**
     * Sets the value of the classificationUsPrimary property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassificationUsPrimary }
     *     
     */
    public void setClassificationUsPrimary(ClassificationUsPrimary value) {
        this.classificationUsPrimary = value;
    }

    /**
     * Gets the value of the classificationUsSecondary property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the classificationUsSecondary property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClassificationUsSecondary().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ClassificationUsSecondary }
     * 
     * 
     */
    public List<ClassificationUsSecondary> getClassificationUsSecondary() {
        if (classificationUsSecondary == null) {
            classificationUsSecondary = new ArrayList<ClassificationUsSecondary>();
        }
        return this.classificationUsSecondary;
    }

}
