//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.10 at 07:08:34 PM EST 
//


package xml.us.patent.application.v16;

import java.util.ArrayList;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "miOrMnOrMoOrMtextOrMsOrMspaceOrMprescriptsOrNoneOrMrowOrMfracOrMsqrtOrMrootOrMstyleOrMerrorOrMpaddedOrMphantomOrMfencedOrMsubOrMsupOrMsubsupOrMunderOrMoverOrMunderoverOrMmultiscriptsOrMtableOrMtrOrMtdOrMaligngroupOrMalignmarkOrMactionOrCiOrCnOrApplyOrFnOrLambdaOrRelnOrIntervalOrListOrMatrixOrMatrixrowOrSetOrVectorOrSemantics"
})
@XmlRootElement(name = "mstyle")
public class Mstyle {

    @XmlAttribute(name = "fontsize")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String fontsize;
    @XmlAttribute(name = "fontweight")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String fontweight;
    @XmlAttribute(name = "fontstyle")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String fontstyle;
    @XmlAttribute(name = "fontfamily")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String fontfamily;
    @XmlAttribute(name = "color")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String color;
    @XmlAttribute(name = "form")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String form;
    @XmlAttribute(name = "fence")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String fence;
    @XmlAttribute(name = "separator")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String separator;
    @XmlAttribute(name = "lspace")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String lspace;
    @XmlAttribute(name = "rspace")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String rspace;
    @XmlAttribute(name = "stretchy")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String stretchy;
    @XmlAttribute(name = "symmetric")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String symmetric;
    @XmlAttribute(name = "maxsize")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String maxsize;
    @XmlAttribute(name = "minsize")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String minsize;
    @XmlAttribute(name = "largeop")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String largeop;
    @XmlAttribute(name = "movablelimits")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String movablelimits;
    @XmlAttribute(name = "accent")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String accent;
    @XmlAttribute(name = "lquote")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String lquote;
    @XmlAttribute(name = "rquote")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String rquote;
    @XmlAttribute(name = "linethickness")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String linethickness;
    @XmlAttribute(name = "scriptlevel")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String scriptlevel;
    @XmlAttribute(name = "scriptsizemultiplier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String scriptsizemultiplier;
    @XmlAttribute(name = "scriptminsize")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String scriptminsize;
    @XmlAttribute(name = "background")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String background;
    @XmlAttribute(name = "open")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String open;
    @XmlAttribute(name = "close")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String close;
    @XmlAttribute(name = "separators")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String separators;
    @XmlAttribute(name = "subscriptshift")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String subscriptshift;
    @XmlAttribute(name = "superscriptshift")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String superscriptshift;
    @XmlAttribute(name = "accentunder")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String accentunder;
    @XmlAttribute(name = "align")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String align;
    @XmlAttribute(name = "rowalign")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String rowalign;
    @XmlAttribute(name = "columnalign")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String columnalign;
    @XmlAttribute(name = "groupalign")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String groupalign;
    @XmlAttribute(name = "alignmentscope")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String alignmentscope;
    @XmlAttribute(name = "rowspacing")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String rowspacing;
    @XmlAttribute(name = "columnspacing")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String columnspacing;
    @XmlAttribute(name = "rowlines")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String rowlines;
    @XmlAttribute(name = "columnlines")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String columnlines;
    @XmlAttribute(name = "frame")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String frame;
    @XmlAttribute(name = "framespacing")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String framespacing;
    @XmlAttribute(name = "equalrows")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String equalrows;
    @XmlAttribute(name = "equalcolumns")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String equalcolumns;
    @XmlAttribute(name = "displaystyle")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String displaystyle;
    @XmlAttribute(name = "rowspan")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String rowspan;
    @XmlAttribute(name = "columnspan")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String columnspan;
    @XmlAttribute(name = "edge")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String edge;
    @XmlAttribute(name = "actiontype")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String actiontype;
    @XmlAttribute(name = "selection")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String selection;
    @XmlAttribute(name = "class")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String clazz;
    @XmlAttribute(name = "style")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String style;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    @XmlAttribute(name = "other")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String other;
    @XmlElements({
        @XmlElement(name = "mi", type = Mi.class),
        @XmlElement(name = "mn", type = Mn.class),
        @XmlElement(name = "mo", type = Mo.class),
        @XmlElement(name = "mtext", type = Mtext.class),
        @XmlElement(name = "ms", type = Ms.class),
        @XmlElement(name = "mspace", type = Mspace.class),
        @XmlElement(name = "mprescripts", type = Mprescripts.class),
        @XmlElement(name = "none", type = None.class),
        @XmlElement(name = "mrow", type = Mrow.class),
        @XmlElement(name = "mfrac", type = Mfrac.class),
        @XmlElement(name = "msqrt", type = Msqrt.class),
        @XmlElement(name = "mroot", type = Mroot.class),
        @XmlElement(name = "mstyle", type = Mstyle.class),
        @XmlElement(name = "merror", type = Merror.class),
        @XmlElement(name = "mpadded", type = Mpadded.class),
        @XmlElement(name = "mphantom", type = Mphantom.class),
        @XmlElement(name = "mfenced", type = Mfenced.class),
        @XmlElement(name = "msub", type = Msub.class),
        @XmlElement(name = "msup", type = Msup.class),
        @XmlElement(name = "msubsup", type = Msubsup.class),
        @XmlElement(name = "munder", type = Munder.class),
        @XmlElement(name = "mover", type = Mover.class),
        @XmlElement(name = "munderover", type = Munderover.class),
        @XmlElement(name = "mmultiscripts", type = Mmultiscripts.class),
        @XmlElement(name = "mtable", type = Mtable.class),
        @XmlElement(name = "mtr", type = Mtr.class),
        @XmlElement(name = "mtd", type = Mtd.class),
        @XmlElement(name = "maligngroup", type = Maligngroup.class),
        @XmlElement(name = "malignmark", type = Malignmark.class),
        @XmlElement(name = "maction", type = Maction.class),
        @XmlElement(name = "ci", type = Ci.class),
        @XmlElement(name = "cn", type = Cn.class),
        @XmlElement(name = "apply", type = Apply.class),
        @XmlElement(name = "fn", type = Fn.class),
        @XmlElement(name = "lambda", type = Lambda.class),
        @XmlElement(name = "reln", type = Reln.class),
        @XmlElement(name = "interval", type = Interval.class),
        @XmlElement(name = "list", type = xml.us.patent.application.v16.List.class),
        @XmlElement(name = "matrix", type = Matrix.class),
        @XmlElement(name = "matrixrow", type = Matrixrow.class),
        @XmlElement(name = "set", type = Set.class),
        @XmlElement(name = "vector", type = Vector.class),
        @XmlElement(name = "semantics", type = Semantics.class)
    })
    protected java.util.List<Object> miOrMnOrMoOrMtextOrMsOrMspaceOrMprescriptsOrNoneOrMrowOrMfracOrMsqrtOrMrootOrMstyleOrMerrorOrMpaddedOrMphantomOrMfencedOrMsubOrMsupOrMsubsupOrMunderOrMoverOrMunderoverOrMmultiscriptsOrMtableOrMtrOrMtdOrMaligngroupOrMalignmarkOrMactionOrCiOrCnOrApplyOrFnOrLambdaOrRelnOrIntervalOrListOrMatrixOrMatrixrowOrSetOrVectorOrSemantics;

    /**
     * Gets the value of the fontsize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFontsize() {
        return fontsize;
    }

    /**
     * Sets the value of the fontsize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFontsize(String value) {
        this.fontsize = value;
    }

    /**
     * Gets the value of the fontweight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFontweight() {
        return fontweight;
    }

    /**
     * Sets the value of the fontweight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFontweight(String value) {
        this.fontweight = value;
    }

    /**
     * Gets the value of the fontstyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFontstyle() {
        return fontstyle;
    }

    /**
     * Sets the value of the fontstyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFontstyle(String value) {
        this.fontstyle = value;
    }

    /**
     * Gets the value of the fontfamily property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFontfamily() {
        return fontfamily;
    }

    /**
     * Sets the value of the fontfamily property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFontfamily(String value) {
        this.fontfamily = value;
    }

    /**
     * Gets the value of the color property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColor() {
        return color;
    }

    /**
     * Sets the value of the color property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColor(String value) {
        this.color = value;
    }

    /**
     * Gets the value of the form property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForm() {
        return form;
    }

    /**
     * Sets the value of the form property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForm(String value) {
        this.form = value;
    }

    /**
     * Gets the value of the fence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFence() {
        return fence;
    }

    /**
     * Sets the value of the fence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFence(String value) {
        this.fence = value;
    }

    /**
     * Gets the value of the separator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeparator() {
        return separator;
    }

    /**
     * Sets the value of the separator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeparator(String value) {
        this.separator = value;
    }

    /**
     * Gets the value of the lspace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLspace() {
        return lspace;
    }

    /**
     * Sets the value of the lspace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLspace(String value) {
        this.lspace = value;
    }

    /**
     * Gets the value of the rspace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRspace() {
        return rspace;
    }

    /**
     * Sets the value of the rspace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRspace(String value) {
        this.rspace = value;
    }

    /**
     * Gets the value of the stretchy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStretchy() {
        return stretchy;
    }

    /**
     * Sets the value of the stretchy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStretchy(String value) {
        this.stretchy = value;
    }

    /**
     * Gets the value of the symmetric property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSymmetric() {
        return symmetric;
    }

    /**
     * Sets the value of the symmetric property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSymmetric(String value) {
        this.symmetric = value;
    }

    /**
     * Gets the value of the maxsize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxsize() {
        return maxsize;
    }

    /**
     * Sets the value of the maxsize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxsize(String value) {
        this.maxsize = value;
    }

    /**
     * Gets the value of the minsize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinsize() {
        return minsize;
    }

    /**
     * Sets the value of the minsize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinsize(String value) {
        this.minsize = value;
    }

    /**
     * Gets the value of the largeop property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLargeop() {
        return largeop;
    }

    /**
     * Sets the value of the largeop property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLargeop(String value) {
        this.largeop = value;
    }

    /**
     * Gets the value of the movablelimits property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMovablelimits() {
        return movablelimits;
    }

    /**
     * Sets the value of the movablelimits property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMovablelimits(String value) {
        this.movablelimits = value;
    }

    /**
     * Gets the value of the accent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccent() {
        return accent;
    }

    /**
     * Sets the value of the accent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccent(String value) {
        this.accent = value;
    }

    /**
     * Gets the value of the lquote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLquote() {
        return lquote;
    }

    /**
     * Sets the value of the lquote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLquote(String value) {
        this.lquote = value;
    }

    /**
     * Gets the value of the rquote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRquote() {
        return rquote;
    }

    /**
     * Sets the value of the rquote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRquote(String value) {
        this.rquote = value;
    }

    /**
     * Gets the value of the linethickness property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinethickness() {
        return linethickness;
    }

    /**
     * Sets the value of the linethickness property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinethickness(String value) {
        this.linethickness = value;
    }

    /**
     * Gets the value of the scriptlevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScriptlevel() {
        return scriptlevel;
    }

    /**
     * Sets the value of the scriptlevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScriptlevel(String value) {
        this.scriptlevel = value;
    }

    /**
     * Gets the value of the scriptsizemultiplier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScriptsizemultiplier() {
        return scriptsizemultiplier;
    }

    /**
     * Sets the value of the scriptsizemultiplier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScriptsizemultiplier(String value) {
        this.scriptsizemultiplier = value;
    }

    /**
     * Gets the value of the scriptminsize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScriptminsize() {
        return scriptminsize;
    }

    /**
     * Sets the value of the scriptminsize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScriptminsize(String value) {
        this.scriptminsize = value;
    }

    /**
     * Gets the value of the background property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackground() {
        return background;
    }

    /**
     * Sets the value of the background property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackground(String value) {
        this.background = value;
    }

    /**
     * Gets the value of the open property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpen() {
        return open;
    }

    /**
     * Sets the value of the open property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpen(String value) {
        this.open = value;
    }

    /**
     * Gets the value of the close property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClose() {
        return close;
    }

    /**
     * Sets the value of the close property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClose(String value) {
        this.close = value;
    }

    /**
     * Gets the value of the separators property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeparators() {
        return separators;
    }

    /**
     * Sets the value of the separators property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeparators(String value) {
        this.separators = value;
    }

    /**
     * Gets the value of the subscriptshift property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubscriptshift() {
        return subscriptshift;
    }

    /**
     * Sets the value of the subscriptshift property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubscriptshift(String value) {
        this.subscriptshift = value;
    }

    /**
     * Gets the value of the superscriptshift property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuperscriptshift() {
        return superscriptshift;
    }

    /**
     * Sets the value of the superscriptshift property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuperscriptshift(String value) {
        this.superscriptshift = value;
    }

    /**
     * Gets the value of the accentunder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccentunder() {
        return accentunder;
    }

    /**
     * Sets the value of the accentunder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccentunder(String value) {
        this.accentunder = value;
    }

    /**
     * Gets the value of the align property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlign() {
        return align;
    }

    /**
     * Sets the value of the align property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlign(String value) {
        this.align = value;
    }

    /**
     * Gets the value of the rowalign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRowalign() {
        return rowalign;
    }

    /**
     * Sets the value of the rowalign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRowalign(String value) {
        this.rowalign = value;
    }

    /**
     * Gets the value of the columnalign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColumnalign() {
        return columnalign;
    }

    /**
     * Sets the value of the columnalign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColumnalign(String value) {
        this.columnalign = value;
    }

    /**
     * Gets the value of the groupalign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupalign() {
        return groupalign;
    }

    /**
     * Sets the value of the groupalign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupalign(String value) {
        this.groupalign = value;
    }

    /**
     * Gets the value of the alignmentscope property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlignmentscope() {
        return alignmentscope;
    }

    /**
     * Sets the value of the alignmentscope property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlignmentscope(String value) {
        this.alignmentscope = value;
    }

    /**
     * Gets the value of the rowspacing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRowspacing() {
        return rowspacing;
    }

    /**
     * Sets the value of the rowspacing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRowspacing(String value) {
        this.rowspacing = value;
    }

    /**
     * Gets the value of the columnspacing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColumnspacing() {
        return columnspacing;
    }

    /**
     * Sets the value of the columnspacing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColumnspacing(String value) {
        this.columnspacing = value;
    }

    /**
     * Gets the value of the rowlines property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRowlines() {
        return rowlines;
    }

    /**
     * Sets the value of the rowlines property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRowlines(String value) {
        this.rowlines = value;
    }

    /**
     * Gets the value of the columnlines property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColumnlines() {
        return columnlines;
    }

    /**
     * Sets the value of the columnlines property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColumnlines(String value) {
        this.columnlines = value;
    }

    /**
     * Gets the value of the frame property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrame() {
        return frame;
    }

    /**
     * Sets the value of the frame property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrame(String value) {
        this.frame = value;
    }

    /**
     * Gets the value of the framespacing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFramespacing() {
        return framespacing;
    }

    /**
     * Sets the value of the framespacing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFramespacing(String value) {
        this.framespacing = value;
    }

    /**
     * Gets the value of the equalrows property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEqualrows() {
        return equalrows;
    }

    /**
     * Sets the value of the equalrows property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqualrows(String value) {
        this.equalrows = value;
    }

    /**
     * Gets the value of the equalcolumns property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEqualcolumns() {
        return equalcolumns;
    }

    /**
     * Sets the value of the equalcolumns property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqualcolumns(String value) {
        this.equalcolumns = value;
    }

    /**
     * Gets the value of the displaystyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplaystyle() {
        return displaystyle;
    }

    /**
     * Sets the value of the displaystyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplaystyle(String value) {
        this.displaystyle = value;
    }

    /**
     * Gets the value of the rowspan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRowspan() {
        return rowspan;
    }

    /**
     * Sets the value of the rowspan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRowspan(String value) {
        this.rowspan = value;
    }

    /**
     * Gets the value of the columnspan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColumnspan() {
        return columnspan;
    }

    /**
     * Sets the value of the columnspan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColumnspan(String value) {
        this.columnspan = value;
    }

    /**
     * Gets the value of the edge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEdge() {
        return edge;
    }

    /**
     * Sets the value of the edge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEdge(String value) {
        this.edge = value;
    }

    /**
     * Gets the value of the actiontype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActiontype() {
        return actiontype;
    }

    /**
     * Sets the value of the actiontype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActiontype(String value) {
        this.actiontype = value;
    }

    /**
     * Gets the value of the selection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSelection() {
        return selection;
    }

    /**
     * Sets the value of the selection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelection(String value) {
        this.selection = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClazz(String value) {
        this.clazz = value;
    }

    /**
     * Gets the value of the style property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStyle() {
        return style;
    }

    /**
     * Sets the value of the style property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStyle(String value) {
        this.style = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the other property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOther() {
        return other;
    }

    /**
     * Sets the value of the other property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOther(String value) {
        this.other = value;
    }

    /**
     * Gets the value of the miOrMnOrMoOrMtextOrMsOrMspaceOrMprescriptsOrNoneOrMrowOrMfracOrMsqrtOrMrootOrMstyleOrMerrorOrMpaddedOrMphantomOrMfencedOrMsubOrMsupOrMsubsupOrMunderOrMoverOrMunderoverOrMmultiscriptsOrMtableOrMtrOrMtdOrMaligngroupOrMalignmarkOrMactionOrCiOrCnOrApplyOrFnOrLambdaOrRelnOrIntervalOrListOrMatrixOrMatrixrowOrSetOrVectorOrSemantics property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the miOrMnOrMoOrMtextOrMsOrMspaceOrMprescriptsOrNoneOrMrowOrMfracOrMsqrtOrMrootOrMstyleOrMerrorOrMpaddedOrMphantomOrMfencedOrMsubOrMsupOrMsubsupOrMunderOrMoverOrMunderoverOrMmultiscriptsOrMtableOrMtrOrMtdOrMaligngroupOrMalignmarkOrMactionOrCiOrCnOrApplyOrFnOrLambdaOrRelnOrIntervalOrListOrMatrixOrMatrixrowOrSetOrVectorOrSemantics property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMiOrMnOrMoOrMtextOrMsOrMspaceOrMprescriptsOrNoneOrMrowOrMfracOrMsqrtOrMrootOrMstyleOrMerrorOrMpaddedOrMphantomOrMfencedOrMsubOrMsupOrMsubsupOrMunderOrMoverOrMunderoverOrMmultiscriptsOrMtableOrMtrOrMtdOrMaligngroupOrMalignmarkOrMactionOrCiOrCnOrApplyOrFnOrLambdaOrRelnOrIntervalOrListOrMatrixOrMatrixrowOrSetOrVectorOrSemantics().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Mi }
     * {@link Mn }
     * {@link Mo }
     * {@link Mtext }
     * {@link Ms }
     * {@link Mspace }
     * {@link Mprescripts }
     * {@link None }
     * {@link Mrow }
     * {@link Mfrac }
     * {@link Msqrt }
     * {@link Mroot }
     * {@link Mstyle }
     * {@link Merror }
     * {@link Mpadded }
     * {@link Mphantom }
     * {@link Mfenced }
     * {@link Msub }
     * {@link Msup }
     * {@link Msubsup }
     * {@link Munder }
     * {@link Mover }
     * {@link Munderover }
     * {@link Mmultiscripts }
     * {@link Mtable }
     * {@link Mtr }
     * {@link Mtd }
     * {@link Maligngroup }
     * {@link Malignmark }
     * {@link Maction }
     * {@link Ci }
     * {@link Cn }
     * {@link Apply }
     * {@link Fn }
     * {@link Lambda }
     * {@link Reln }
     * {@link Interval }
     * {@link xml.us.patent.application.v16.List }
     * {@link Matrix }
     * {@link Matrixrow }
     * {@link Set }
     * {@link Vector }
     * {@link Semantics }
     * 
     * 
     */
    public java.util.List<Object> getMiOrMnOrMoOrMtextOrMsOrMspaceOrMprescriptsOrNoneOrMrowOrMfracOrMsqrtOrMrootOrMstyleOrMerrorOrMpaddedOrMphantomOrMfencedOrMsubOrMsupOrMsubsupOrMunderOrMoverOrMunderoverOrMmultiscriptsOrMtableOrMtrOrMtdOrMaligngroupOrMalignmarkOrMactionOrCiOrCnOrApplyOrFnOrLambdaOrRelnOrIntervalOrListOrMatrixOrMatrixrowOrSetOrVectorOrSemantics() {
        if (miOrMnOrMoOrMtextOrMsOrMspaceOrMprescriptsOrNoneOrMrowOrMfracOrMsqrtOrMrootOrMstyleOrMerrorOrMpaddedOrMphantomOrMfencedOrMsubOrMsupOrMsubsupOrMunderOrMoverOrMunderoverOrMmultiscriptsOrMtableOrMtrOrMtdOrMaligngroupOrMalignmarkOrMactionOrCiOrCnOrApplyOrFnOrLambdaOrRelnOrIntervalOrListOrMatrixOrMatrixrowOrSetOrVectorOrSemantics == null) {
            miOrMnOrMoOrMtextOrMsOrMspaceOrMprescriptsOrNoneOrMrowOrMfracOrMsqrtOrMrootOrMstyleOrMerrorOrMpaddedOrMphantomOrMfencedOrMsubOrMsupOrMsubsupOrMunderOrMoverOrMunderoverOrMmultiscriptsOrMtableOrMtrOrMtdOrMaligngroupOrMalignmarkOrMactionOrCiOrCnOrApplyOrFnOrLambdaOrRelnOrIntervalOrListOrMatrixOrMatrixrowOrSetOrVectorOrSemantics = new ArrayList<Object>();
        }
        return this.miOrMnOrMoOrMtextOrMsOrMspaceOrMprescriptsOrNoneOrMrowOrMfracOrMsqrtOrMrootOrMstyleOrMerrorOrMpaddedOrMphantomOrMfencedOrMsubOrMsupOrMsubsupOrMunderOrMoverOrMunderoverOrMmultiscriptsOrMtableOrMtrOrMtdOrMaligngroupOrMalignmarkOrMactionOrCiOrCnOrApplyOrFnOrLambdaOrRelnOrIntervalOrListOrMatrixOrMatrixrowOrSetOrVectorOrSemantics;
    }

}
