//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.10 at 07:08:34 PM EST 
//


package xml.us.patent.application.v16;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "s130",
    "s160",
    "s170"
})
@XmlRootElement(name = "s100")
public class S100 {

    protected String s130;
    @XmlElement(required = true)
    protected String s160;
    protected String s170;

    /**
     * Gets the value of the s130 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getS130() {
        return s130;
    }

    /**
     * Sets the value of the s130 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setS130(String value) {
        this.s130 = value;
    }

    /**
     * Gets the value of the s160 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getS160() {
        return s160;
    }

    /**
     * Sets the value of the s160 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setS160(String value) {
        this.s160 = value;
    }

    /**
     * Gets the value of the s170 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getS170() {
        return s170;
    }

    /**
     * Sets the value of the s170 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setS170(String value) {
        this.s170 = value;
    }

}
