//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.10 at 07:08:34 PM EST 
//


package xml.us.patent.application.v16;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "s1IxA",
    "s1IxB",
    "s1IxC"
})
@XmlRootElement(name = "s-1-ix")
public class S1Ix {

    @XmlElement(name = "s-1-ix-a", required = true)
    protected S1IxA s1IxA;
    @XmlElement(name = "s-1-ix-b", required = true)
    protected String s1IxB;
    @XmlElement(name = "s-1-ix-c", required = true)
    protected String s1IxC;

    /**
     * Gets the value of the s1IxA property.
     * 
     * @return
     *     possible object is
     *     {@link S1IxA }
     *     
     */
    public S1IxA getS1IxA() {
        return s1IxA;
    }

    /**
     * Sets the value of the s1IxA property.
     * 
     * @param value
     *     allowed object is
     *     {@link S1IxA }
     *     
     */
    public void setS1IxA(S1IxA value) {
        this.s1IxA = value;
    }

    /**
     * Gets the value of the s1IxB property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getS1IxB() {
        return s1IxB;
    }

    /**
     * Sets the value of the s1IxB property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setS1IxB(String value) {
        this.s1IxB = value;
    }

    /**
     * Gets the value of the s1IxC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getS1IxC() {
        return s1IxC;
    }

    /**
     * Sets the value of the s1IxC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setS1IxC(String value) {
        this.s1IxC = value;
    }

}
