//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.10 at 07:08:34 PM EST 
//


package xml.us.patent.application.v16;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "s1VA",
    "s1VB",
    "s1VC",
    "s1VD"
})
@XmlRootElement(name = "s-1-v")
public class S1V {

    @XmlElement(name = "s-1-v-a", required = true)
    protected String s1VA;
    @XmlElement(name = "s-1-v-b", required = true)
    protected String s1VB;
    @XmlElement(name = "s-1-v-c", required = true)
    protected String s1VC;
    @XmlElement(name = "s-1-v-d", required = true)
    protected String s1VD;

    /**
     * Gets the value of the s1VA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getS1VA() {
        return s1VA;
    }

    /**
     * Sets the value of the s1VA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setS1VA(String value) {
        this.s1VA = value;
    }

    /**
     * Gets the value of the s1VB property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getS1VB() {
        return s1VB;
    }

    /**
     * Sets the value of the s1VB property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setS1VB(String value) {
        this.s1VB = value;
    }

    /**
     * Gets the value of the s1VC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getS1VC() {
        return s1VC;
    }

    /**
     * Sets the value of the s1VC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setS1VC(String value) {
        this.s1VC = value;
    }

    /**
     * Gets the value of the s1VD property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getS1VD() {
        return s1VD;
    }

    /**
     * Sets the value of the s1VD property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setS1VD(String value) {
        this.s1VD = value;
    }

}
