//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.10 at 07:08:34 PM EST 
//


package xml.us.patent.application.v16;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "s2IiMt",
    "s2IiA"
})
@XmlRootElement(name = "s-2-ii")
public class S2Ii {

    @XmlElement(name = "s-2-ii-mt", required = true)
    protected String s2IiMt;
    @XmlElement(name = "s-2-ii-a")
    protected String s2IiA;

    /**
     * Gets the value of the s2IiMt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getS2IiMt() {
        return s2IiMt;
    }

    /**
     * Sets the value of the s2IiMt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setS2IiMt(String value) {
        this.s2IiMt = value;
    }

    /**
     * Gets the value of the s2IiA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getS2IiA() {
        return s2IiA;
    }

    /**
     * Sets the value of the s2IiA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setS2IiA(String value) {
        this.s2IiA = value;
    }

}
