//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.10 at 07:08:34 PM EST 
//


package xml.us.patent.application.v16;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "s2IxA",
    "s2IxB",
    "s2IxC",
    "s2IxD"
})
@XmlRootElement(name = "s-2-ix")
public class S2Ix {

    @XmlElement(name = "s-2-ix-a")
    protected String s2IxA;
    @XmlElement(name = "s-2-ix-b")
    protected String s2IxB;
    @XmlElement(name = "s-2-ix-c")
    protected String s2IxC;
    @XmlElement(name = "s-2-ix-d")
    protected String s2IxD;

    /**
     * Gets the value of the s2IxA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getS2IxA() {
        return s2IxA;
    }

    /**
     * Sets the value of the s2IxA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setS2IxA(String value) {
        this.s2IxA = value;
    }

    /**
     * Gets the value of the s2IxB property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getS2IxB() {
        return s2IxB;
    }

    /**
     * Sets the value of the s2IxB property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setS2IxB(String value) {
        this.s2IxB = value;
    }

    /**
     * Gets the value of the s2IxC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getS2IxC() {
        return s2IxC;
    }

    /**
     * Sets the value of the s2IxC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setS2IxC(String value) {
        this.s2IxC = value;
    }

    /**
     * Gets the value of the s2IxD property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getS2IxD() {
        return s2IxD;
    }

    /**
     * Sets the value of the s2IxD property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setS2IxD(String value) {
        this.s2IxD = value;
    }

}
