//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.10 at 07:08:34 PM EST 
//


package xml.us.patent.application.v16;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "s2ViiiA",
    "s2ViiiB",
    "s2ViiiC"
})
@XmlRootElement(name = "s-2-viii")
public class S2Viii {

    @XmlElement(name = "s-2-viii-a")
    protected String s2ViiiA;
    @XmlElement(name = "s-2-viii-b")
    protected String s2ViiiB;
    @XmlElement(name = "s-2-viii-c")
    protected String s2ViiiC;

    /**
     * Gets the value of the s2ViiiA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getS2ViiiA() {
        return s2ViiiA;
    }

    /**
     * Sets the value of the s2ViiiA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setS2ViiiA(String value) {
        this.s2ViiiA = value;
    }

    /**
     * Gets the value of the s2ViiiB property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getS2ViiiB() {
        return s2ViiiB;
    }

    /**
     * Sets the value of the s2ViiiB property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setS2ViiiB(String value) {
        this.s2ViiiB = value;
    }

    /**
     * Gets the value of the s2ViiiC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getS2ViiiC() {
        return s2ViiiC;
    }

    /**
     * Sets the value of the s2ViiiC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setS2ViiiC(String value) {
        this.s2ViiiC = value;
    }

}
