//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.10 at 07:08:34 PM EST 
//


package xml.us.patent.application.v16;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "s2XA",
    "s2XB",
    "s2XC",
    "s2XD",
    "s2XE",
    "s2XF",
    "s2XG",
    "s2XH",
    "s2XI",
    "s2XJ",
    "s2XK"
})
@XmlRootElement(name = "s-2-x")
public class S2X {

    @XmlElement(name = "s-2-x-a")
    protected S2XA s2XA;
    @XmlElement(name = "s-2-x-b")
    protected String s2XB;
    @XmlElement(name = "s-2-x-c")
    protected String s2XC;
    @XmlElement(name = "s-2-x-d")
    protected String s2XD;
    @XmlElement(name = "s-2-x-e")
    protected String s2XE;
    @XmlElement(name = "s-2-x-f")
    protected String s2XF;
    @XmlElement(name = "s-2-x-g")
    protected String s2XG;
    @XmlElement(name = "s-2-x-h")
    protected S2XH s2XH;
    @XmlElement(name = "s-2-x-i")
    protected S2XI s2XI;
    @XmlElement(name = "s-2-x-j")
    protected S2XJ s2XJ;
    @XmlElement(name = "s-2-x-k")
    protected String s2XK;

    /**
     * Gets the value of the s2XA property.
     * 
     * @return
     *     possible object is
     *     {@link S2XA }
     *     
     */
    public S2XA getS2XA() {
        return s2XA;
    }

    /**
     * Sets the value of the s2XA property.
     * 
     * @param value
     *     allowed object is
     *     {@link S2XA }
     *     
     */
    public void setS2XA(S2XA value) {
        this.s2XA = value;
    }

    /**
     * Gets the value of the s2XB property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getS2XB() {
        return s2XB;
    }

    /**
     * Sets the value of the s2XB property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setS2XB(String value) {
        this.s2XB = value;
    }

    /**
     * Gets the value of the s2XC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getS2XC() {
        return s2XC;
    }

    /**
     * Sets the value of the s2XC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setS2XC(String value) {
        this.s2XC = value;
    }

    /**
     * Gets the value of the s2XD property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getS2XD() {
        return s2XD;
    }

    /**
     * Sets the value of the s2XD property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setS2XD(String value) {
        this.s2XD = value;
    }

    /**
     * Gets the value of the s2XE property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getS2XE() {
        return s2XE;
    }

    /**
     * Sets the value of the s2XE property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setS2XE(String value) {
        this.s2XE = value;
    }

    /**
     * Gets the value of the s2XF property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getS2XF() {
        return s2XF;
    }

    /**
     * Sets the value of the s2XF property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setS2XF(String value) {
        this.s2XF = value;
    }

    /**
     * Gets the value of the s2XG property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getS2XG() {
        return s2XG;
    }

    /**
     * Sets the value of the s2XG property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setS2XG(String value) {
        this.s2XG = value;
    }

    /**
     * Gets the value of the s2XH property.
     * 
     * @return
     *     possible object is
     *     {@link S2XH }
     *     
     */
    public S2XH getS2XH() {
        return s2XH;
    }

    /**
     * Sets the value of the s2XH property.
     * 
     * @param value
     *     allowed object is
     *     {@link S2XH }
     *     
     */
    public void setS2XH(S2XH value) {
        this.s2XH = value;
    }

    /**
     * Gets the value of the s2XI property.
     * 
     * @return
     *     possible object is
     *     {@link S2XI }
     *     
     */
    public S2XI getS2XI() {
        return s2XI;
    }

    /**
     * Sets the value of the s2XI property.
     * 
     * @param value
     *     allowed object is
     *     {@link S2XI }
     *     
     */
    public void setS2XI(S2XI value) {
        this.s2XI = value;
    }

    /**
     * Gets the value of the s2XJ property.
     * 
     * @return
     *     possible object is
     *     {@link S2XJ }
     *     
     */
    public S2XJ getS2XJ() {
        return s2XJ;
    }

    /**
     * Sets the value of the s2XJ property.
     * 
     * @param value
     *     allowed object is
     *     {@link S2XJ }
     *     
     */
    public void setS2XJ(S2XJ value) {
        this.s2XJ = value;
    }

    /**
     * Gets the value of the s2XK property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getS2XK() {
        return s2XK;
    }

    /**
     * Sets the value of the s2XK property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setS2XK(String value) {
        this.s2XK = value;
    }

}
