//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.29 at 10:47:01 PM EST 
//


package xml.us.patent.grant.v43;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "publicationReference",
    "usSirFlag",
    "applicationReference",
    "usApplicationSeriesCode",
    "priorityClaims",
    "usIssuedOnContinuedProsecutionApplication",
    "rule47Flag",
    "usTermOfGrant",
    "classificationsIpcr",
    "classificationsCpc",
    "classificationLocarno",
    "classificationNational",
    "inventionTitle",
    "usBotanic",
    "usReferencesCited",
    "numberOfClaims",
    "usExemplaryClaim",
    "usFieldOfClassificationSearch",
    "figures",
    "usMicroformQuantity",
    "usRelatedDocuments",
    "usParties",
    "assignees",
    "examiners",
    "pctOrRegionalFilingData",
    "pctOrRegionalPublishingData",
    "patentFamily",
    "bioDeposit",
    "text"
})
@XmlRootElement(name = "us-bibliographic-data-grant")
public class UsBibliographicDataGrant {

    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    @XmlAttribute(name = "lang")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String lang;
    @XmlAttribute(name = "status")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String status;
    @XmlAttribute(name = "country")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String country;
    @XmlElement(name = "publication-reference", required = true)
    protected PublicationReference publicationReference;
    @XmlElement(name = "us-sir-flag")
    protected UsSirFlag usSirFlag;
    @XmlElement(name = "application-reference", required = true)
    protected ApplicationReference applicationReference;
    @XmlElement(name = "us-application-series-code", required = true)
    protected String usApplicationSeriesCode;
    @XmlElement(name = "priority-claims")
    protected PriorityClaims priorityClaims;
    @XmlElement(name = "us-issued-on-continued-prosecution-application")
    protected UsIssuedOnContinuedProsecutionApplication usIssuedOnContinuedProsecutionApplication;
    @XmlElement(name = "rule-47-flag")
    protected Rule47Flag rule47Flag;
    @XmlElement(name = "us-term-of-grant")
    protected UsTermOfGrant usTermOfGrant;
    @XmlElement(name = "classifications-ipcr")
    protected ClassificationsIpcr classificationsIpcr;
    @XmlElement(name = "classifications-cpc")
    protected ClassificationsCpc classificationsCpc;
    @XmlElement(name = "classification-locarno")
    protected ClassificationLocarno classificationLocarno;
    @XmlElement(name = "classification-national")
    protected ClassificationNational classificationNational;
    @XmlElement(name = "invention-title", required = true)
    protected InventionTitle inventionTitle;
    @XmlElement(name = "us-botanic")
    protected UsBotanic usBotanic;
    @XmlElement(name = "us-references-cited")
    protected UsReferencesCited usReferencesCited;
    @XmlElement(name = "number-of-claims")
    protected String numberOfClaims;
    @XmlElement(name = "us-exemplary-claim")
    protected List<UsExemplaryClaim> usExemplaryClaim;
    @XmlElement(name = "us-field-of-classification-search")
    protected UsFieldOfClassificationSearch usFieldOfClassificationSearch;
    protected Figures figures;
    @XmlElement(name = "us-microform-quantity")
    protected String usMicroformQuantity;
    @XmlElement(name = "us-related-documents")
    protected UsRelatedDocuments usRelatedDocuments;
    @XmlElement(name = "us-parties", required = true)
    protected UsParties usParties;
    protected Assignees assignees;
    protected Examiners examiners;
    @XmlElement(name = "pct-or-regional-filing-data")
    protected PctOrRegionalFilingData pctOrRegionalFilingData;
    @XmlElement(name = "pct-or-regional-publishing-data")
    protected PctOrRegionalPublishingData pctOrRegionalPublishingData;
    @XmlElement(name = "patent-family")
    protected PatentFamily patentFamily;
    @XmlElement(name = "bio-deposit")
    protected BioDeposit bioDeposit;
    protected List<Text> text;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the publicationReference property.
     * 
     * @return
     *     possible object is
     *     {@link PublicationReference }
     *     
     */
    public PublicationReference getPublicationReference() {
        return publicationReference;
    }

    /**
     * Sets the value of the publicationReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublicationReference }
     *     
     */
    public void setPublicationReference(PublicationReference value) {
        this.publicationReference = value;
    }

    /**
     * Gets the value of the usSirFlag property.
     * 
     * @return
     *     possible object is
     *     {@link UsSirFlag }
     *     
     */
    public UsSirFlag getUsSirFlag() {
        return usSirFlag;
    }

    /**
     * Sets the value of the usSirFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsSirFlag }
     *     
     */
    public void setUsSirFlag(UsSirFlag value) {
        this.usSirFlag = value;
    }

    /**
     * Gets the value of the applicationReference property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationReference }
     *     
     */
    public ApplicationReference getApplicationReference() {
        return applicationReference;
    }

    /**
     * Sets the value of the applicationReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationReference }
     *     
     */
    public void setApplicationReference(ApplicationReference value) {
        this.applicationReference = value;
    }

    /**
     * Gets the value of the usApplicationSeriesCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsApplicationSeriesCode() {
        return usApplicationSeriesCode;
    }

    /**
     * Sets the value of the usApplicationSeriesCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsApplicationSeriesCode(String value) {
        this.usApplicationSeriesCode = value;
    }

    /**
     * Gets the value of the priorityClaims property.
     * 
     * @return
     *     possible object is
     *     {@link PriorityClaims }
     *     
     */
    public PriorityClaims getPriorityClaims() {
        return priorityClaims;
    }

    /**
     * Sets the value of the priorityClaims property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriorityClaims }
     *     
     */
    public void setPriorityClaims(PriorityClaims value) {
        this.priorityClaims = value;
    }

    /**
     * Gets the value of the usIssuedOnContinuedProsecutionApplication property.
     * 
     * @return
     *     possible object is
     *     {@link UsIssuedOnContinuedProsecutionApplication }
     *     
     */
    public UsIssuedOnContinuedProsecutionApplication getUsIssuedOnContinuedProsecutionApplication() {
        return usIssuedOnContinuedProsecutionApplication;
    }

    /**
     * Sets the value of the usIssuedOnContinuedProsecutionApplication property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsIssuedOnContinuedProsecutionApplication }
     *     
     */
    public void setUsIssuedOnContinuedProsecutionApplication(UsIssuedOnContinuedProsecutionApplication value) {
        this.usIssuedOnContinuedProsecutionApplication = value;
    }

    /**
     * Gets the value of the rule47Flag property.
     * 
     * @return
     *     possible object is
     *     {@link Rule47Flag }
     *     
     */
    public Rule47Flag getRule47Flag() {
        return rule47Flag;
    }

    /**
     * Sets the value of the rule47Flag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rule47Flag }
     *     
     */
    public void setRule47Flag(Rule47Flag value) {
        this.rule47Flag = value;
    }

    /**
     * Gets the value of the usTermOfGrant property.
     * 
     * @return
     *     possible object is
     *     {@link UsTermOfGrant }
     *     
     */
    public UsTermOfGrant getUsTermOfGrant() {
        return usTermOfGrant;
    }

    /**
     * Sets the value of the usTermOfGrant property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsTermOfGrant }
     *     
     */
    public void setUsTermOfGrant(UsTermOfGrant value) {
        this.usTermOfGrant = value;
    }

    /**
     * Gets the value of the classificationsIpcr property.
     * 
     * @return
     *     possible object is
     *     {@link ClassificationsIpcr }
     *     
     */
    public ClassificationsIpcr getClassificationsIpcr() {
        return classificationsIpcr;
    }

    /**
     * Sets the value of the classificationsIpcr property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassificationsIpcr }
     *     
     */
    public void setClassificationsIpcr(ClassificationsIpcr value) {
        this.classificationsIpcr = value;
    }

    /**
     * Gets the value of the classificationsCpc property.
     * 
     * @return
     *     possible object is
     *     {@link ClassificationsCpc }
     *     
     */
    public ClassificationsCpc getClassificationsCpc() {
        return classificationsCpc;
    }

    /**
     * Sets the value of the classificationsCpc property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassificationsCpc }
     *     
     */
    public void setClassificationsCpc(ClassificationsCpc value) {
        this.classificationsCpc = value;
    }

    /**
     * Gets the value of the classificationLocarno property.
     * 
     * @return
     *     possible object is
     *     {@link ClassificationLocarno }
     *     
     */
    public ClassificationLocarno getClassificationLocarno() {
        return classificationLocarno;
    }

    /**
     * Sets the value of the classificationLocarno property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassificationLocarno }
     *     
     */
    public void setClassificationLocarno(ClassificationLocarno value) {
        this.classificationLocarno = value;
    }

    /**
     * Gets the value of the classificationNational property.
     * 
     * @return
     *     possible object is
     *     {@link ClassificationNational }
     *     
     */
    public ClassificationNational getClassificationNational() {
        return classificationNational;
    }

    /**
     * Sets the value of the classificationNational property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassificationNational }
     *     
     */
    public void setClassificationNational(ClassificationNational value) {
        this.classificationNational = value;
    }

    /**
     * Gets the value of the inventionTitle property.
     * 
     * @return
     *     possible object is
     *     {@link InventionTitle }
     *     
     */
    public InventionTitle getInventionTitle() {
        return inventionTitle;
    }

    /**
     * Sets the value of the inventionTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link InventionTitle }
     *     
     */
    public void setInventionTitle(InventionTitle value) {
        this.inventionTitle = value;
    }

    /**
     * Gets the value of the usBotanic property.
     * 
     * @return
     *     possible object is
     *     {@link UsBotanic }
     *     
     */
    public UsBotanic getUsBotanic() {
        return usBotanic;
    }

    /**
     * Sets the value of the usBotanic property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsBotanic }
     *     
     */
    public void setUsBotanic(UsBotanic value) {
        this.usBotanic = value;
    }

    /**
     * Gets the value of the usReferencesCited property.
     * 
     * @return
     *     possible object is
     *     {@link UsReferencesCited }
     *     
     */
    public UsReferencesCited getUsReferencesCited() {
        return usReferencesCited;
    }

    /**
     * Sets the value of the usReferencesCited property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsReferencesCited }
     *     
     */
    public void setUsReferencesCited(UsReferencesCited value) {
        this.usReferencesCited = value;
    }

    /**
     * Gets the value of the numberOfClaims property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOfClaims() {
        return numberOfClaims;
    }

    /**
     * Sets the value of the numberOfClaims property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOfClaims(String value) {
        this.numberOfClaims = value;
    }

    /**
     * Gets the value of the usExemplaryClaim property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the usExemplaryClaim property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUsExemplaryClaim().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UsExemplaryClaim }
     * 
     * 
     */
    public List<UsExemplaryClaim> getUsExemplaryClaim() {
        if (usExemplaryClaim == null) {
            usExemplaryClaim = new ArrayList<UsExemplaryClaim>();
        }
        return this.usExemplaryClaim;
    }

    /**
     * Gets the value of the usFieldOfClassificationSearch property.
     * 
     * @return
     *     possible object is
     *     {@link UsFieldOfClassificationSearch }
     *     
     */
    public UsFieldOfClassificationSearch getUsFieldOfClassificationSearch() {
        return usFieldOfClassificationSearch;
    }

    /**
     * Sets the value of the usFieldOfClassificationSearch property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsFieldOfClassificationSearch }
     *     
     */
    public void setUsFieldOfClassificationSearch(UsFieldOfClassificationSearch value) {
        this.usFieldOfClassificationSearch = value;
    }

    /**
     * Gets the value of the figures property.
     * 
     * @return
     *     possible object is
     *     {@link Figures }
     *     
     */
    public Figures getFigures() {
        return figures;
    }

    /**
     * Sets the value of the figures property.
     * 
     * @param value
     *     allowed object is
     *     {@link Figures }
     *     
     */
    public void setFigures(Figures value) {
        this.figures = value;
    }

    /**
     * Gets the value of the usMicroformQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsMicroformQuantity() {
        return usMicroformQuantity;
    }

    /**
     * Sets the value of the usMicroformQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsMicroformQuantity(String value) {
        this.usMicroformQuantity = value;
    }

    /**
     * Gets the value of the usRelatedDocuments property.
     * 
     * @return
     *     possible object is
     *     {@link UsRelatedDocuments }
     *     
     */
    public UsRelatedDocuments getUsRelatedDocuments() {
        return usRelatedDocuments;
    }

    /**
     * Sets the value of the usRelatedDocuments property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsRelatedDocuments }
     *     
     */
    public void setUsRelatedDocuments(UsRelatedDocuments value) {
        this.usRelatedDocuments = value;
    }

    /**
     * Gets the value of the usParties property.
     * 
     * @return
     *     possible object is
     *     {@link UsParties }
     *     
     */
    public UsParties getUsParties() {
        return usParties;
    }

    /**
     * Sets the value of the usParties property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsParties }
     *     
     */
    public void setUsParties(UsParties value) {
        this.usParties = value;
    }

    /**
     * Gets the value of the assignees property.
     * 
     * @return
     *     possible object is
     *     {@link Assignees }
     *     
     */
    public Assignees getAssignees() {
        return assignees;
    }

    /**
     * Sets the value of the assignees property.
     * 
     * @param value
     *     allowed object is
     *     {@link Assignees }
     *     
     */
    public void setAssignees(Assignees value) {
        this.assignees = value;
    }

    /**
     * Gets the value of the examiners property.
     * 
     * @return
     *     possible object is
     *     {@link Examiners }
     *     
     */
    public Examiners getExaminers() {
        return examiners;
    }

    /**
     * Sets the value of the examiners property.
     * 
     * @param value
     *     allowed object is
     *     {@link Examiners }
     *     
     */
    public void setExaminers(Examiners value) {
        this.examiners = value;
    }

    /**
     * Gets the value of the pctOrRegionalFilingData property.
     * 
     * @return
     *     possible object is
     *     {@link PctOrRegionalFilingData }
     *     
     */
    public PctOrRegionalFilingData getPctOrRegionalFilingData() {
        return pctOrRegionalFilingData;
    }

    /**
     * Sets the value of the pctOrRegionalFilingData property.
     * 
     * @param value
     *     allowed object is
     *     {@link PctOrRegionalFilingData }
     *     
     */
    public void setPctOrRegionalFilingData(PctOrRegionalFilingData value) {
        this.pctOrRegionalFilingData = value;
    }

    /**
     * Gets the value of the pctOrRegionalPublishingData property.
     * 
     * @return
     *     possible object is
     *     {@link PctOrRegionalPublishingData }
     *     
     */
    public PctOrRegionalPublishingData getPctOrRegionalPublishingData() {
        return pctOrRegionalPublishingData;
    }

    /**
     * Sets the value of the pctOrRegionalPublishingData property.
     * 
     * @param value
     *     allowed object is
     *     {@link PctOrRegionalPublishingData }
     *     
     */
    public void setPctOrRegionalPublishingData(PctOrRegionalPublishingData value) {
        this.pctOrRegionalPublishingData = value;
    }

    /**
     * Gets the value of the patentFamily property.
     * 
     * @return
     *     possible object is
     *     {@link PatentFamily }
     *     
     */
    public PatentFamily getPatentFamily() {
        return patentFamily;
    }

    /**
     * Sets the value of the patentFamily property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatentFamily }
     *     
     */
    public void setPatentFamily(PatentFamily value) {
        this.patentFamily = value;
    }

    /**
     * Gets the value of the bioDeposit property.
     * 
     * @return
     *     possible object is
     *     {@link BioDeposit }
     *     
     */
    public BioDeposit getBioDeposit() {
        return bioDeposit;
    }

    /**
     * Sets the value of the bioDeposit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BioDeposit }
     *     
     */
    public void setBioDeposit(BioDeposit value) {
        this.bioDeposit = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the text property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Text }
     * 
     * 
     */
    public List<Text> getText() {
        if (text == null) {
            text = new ArrayList<Text>();
        }
        return this.text;
    }

}
