//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.29 at 10:47:01 PM EST 
//


package xml.us.patent.grant.v43;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "usClassificationsIpcrOrClassificationNationalOrClassificationCpcText"
})
@XmlRootElement(name = "us-field-of-classification-search")
public class UsFieldOfClassificationSearch {

    @XmlElements({
        @XmlElement(name = "us-classifications-ipcr", required = true, type = UsClassificationsIpcr.class),
        @XmlElement(name = "classification-national", required = true, type = ClassificationNational.class),
        @XmlElement(name = "classification-cpc-text", required = true, type = ClassificationCpcText.class)
    })
    protected List<Object> usClassificationsIpcrOrClassificationNationalOrClassificationCpcText;

    /**
     * Gets the value of the usClassificationsIpcrOrClassificationNationalOrClassificationCpcText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the usClassificationsIpcrOrClassificationNationalOrClassificationCpcText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUsClassificationsIpcrOrClassificationNationalOrClassificationCpcText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UsClassificationsIpcr }
     * {@link ClassificationNational }
     * {@link ClassificationCpcText }
     * 
     * 
     */
    public List<Object> getUsClassificationsIpcrOrClassificationNationalOrClassificationCpcText() {
        if (usClassificationsIpcrOrClassificationNationalOrClassificationCpcText == null) {
            usClassificationsIpcrOrClassificationNationalOrClassificationCpcText = new ArrayList<Object>();
        }
        return this.usClassificationsIpcrOrClassificationNationalOrClassificationCpcText;
    }

}
