//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.09 at 05:13:01 PM EST 
//


package xml.us.patent.grant.vST32_025xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "b610OrB620OrB630OrB640OrB641USOrB645OrB645USOrB646USOrB660OrB680USOrB690US"
})
@XmlRootElement(name = "B600")
public class B600 {

    @XmlAttribute(name = "INID")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String inid;
    @XmlElements({
        @XmlElement(name = "B610", required = true, type = B610 .class),
        @XmlElement(name = "B620", required = true, type = B620 .class),
        @XmlElement(name = "B630", required = true, type = B630 .class),
        @XmlElement(name = "B640", required = true, type = B640 .class),
        @XmlElement(name = "B641US", required = true, type = B641US.class),
        @XmlElement(name = "B645", required = true, type = B645 .class),
        @XmlElement(name = "B645US", required = true, type = B645US.class),
        @XmlElement(name = "B646US", required = true, type = B646US.class),
        @XmlElement(name = "B660", required = true, type = B660 .class),
        @XmlElement(name = "B680US", required = true, type = B680US.class),
        @XmlElement(name = "B690US", required = true, type = B690US.class)
    })
    protected List<Object> b610OrB620OrB630OrB640OrB641USOrB645OrB645USOrB646USOrB660OrB680USOrB690US;

    /**
     * Gets the value of the inid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINID() {
        if (inid == null) {
            return "[60]";
        } else {
            return inid;
        }
    }

    /**
     * Sets the value of the inid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINID(String value) {
        this.inid = value;
    }

    /**
     * Gets the value of the b610OrB620OrB630OrB640OrB641USOrB645OrB645USOrB646USOrB660OrB680USOrB690US property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the b610OrB620OrB630OrB640OrB641USOrB645OrB645USOrB646USOrB660OrB680USOrB690US property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getB610OrB620OrB630OrB640OrB641USOrB645OrB645USOrB646USOrB660OrB680USOrB690US().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link B610 }
     * {@link B620 }
     * {@link B630 }
     * {@link B640 }
     * {@link B641US }
     * {@link B645 }
     * {@link B645US }
     * {@link B646US }
     * {@link B660 }
     * {@link B680US }
     * {@link B690US }
     * 
     * 
     */
    public List<Object> getB610OrB620OrB630OrB640OrB641USOrB645OrB645USOrB646USOrB660OrB680USOrB690US() {
        if (b610OrB620OrB630OrB640OrB641USOrB645OrB645USOrB646USOrB660OrB680USOrB690US == null) {
            b610OrB620OrB630OrB640OrB641USOrB645OrB645USOrB646USOrB660OrB680USOrB690US = new ArrayList<Object>();
        }
        return this.b610OrB620OrB630OrB640OrB641USOrB645OrB645USOrB646USOrB660OrB680USOrB690US;
    }

}
