//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.09 at 05:13:01 PM EST 
//


package xml.us.patent.grant.vST32_025xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "b861",
    "b864US"
})
@XmlRootElement(name = "B860")
public class B860 {

    @XmlAttribute(name = "INID")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String inid;
    @XmlElement(name = "B861", required = true)
    protected B861 b861;
    @XmlElement(name = "B864US")
    protected B864US b864US;

    /**
     * Gets the value of the inid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINID() {
        if (inid == null) {
            return "[86]";
        } else {
            return inid;
        }
    }

    /**
     * Sets the value of the inid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINID(String value) {
        this.inid = value;
    }

    /**
     * Gets the value of the b861 property.
     * 
     * @return
     *     possible object is
     *     {@link B861 }
     *     
     */
    public B861 getB861() {
        return b861;
    }

    /**
     * Sets the value of the b861 property.
     * 
     * @param value
     *     allowed object is
     *     {@link B861 }
     *     
     */
    public void setB861(B861 value) {
        this.b861 = value;
    }

    /**
     * Gets the value of the b864US property.
     * 
     * @return
     *     possible object is
     *     {@link B864US }
     *     
     */
    public B864US getB864US() {
        return b864US;
    }

    /**
     * Sets the value of the b864US property.
     * 
     * @param value
     *     allowed object is
     *     {@link B864US }
     *     
     */
    public void setB864US(B864US value) {
        this.b864US = value;
    }

}
