//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.09 at 05:13:01 PM EST 
//


package xml.us.patent.grant.vST32_025xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dtOrDD"
})
@XmlRootElement(name = "DL")
public class DL {

    @XmlAttribute(name = "TSIZE")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String tsize;
    @XmlAttribute(name = "COMPACT")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String compact;
    @XmlElements({
        @XmlElement(name = "DT", required = true, type = DT.class),
        @XmlElement(name = "DD", required = true, type = DD.class)
    })
    protected List<Object> dtOrDD;

    /**
     * Gets the value of the tsize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTSIZE() {
        return tsize;
    }

    /**
     * Sets the value of the tsize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTSIZE(String value) {
        this.tsize = value;
    }

    /**
     * Gets the value of the compact property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOMPACT() {
        return compact;
    }

    /**
     * Sets the value of the compact property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOMPACT(String value) {
        this.compact = value;
    }

    /**
     * Gets the value of the dtOrDD property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dtOrDD property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDTOrDD().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DT }
     * {@link DD }
     * 
     * 
     */
    public List<Object> getDTOrDD() {
        if (dtOrDD == null) {
            dtOrDD = new ArrayList<Object>();
        }
        return this.dtOrDD;
    }

}
