//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.09 at 05:13:01 PM EST 
//


package xml.us.patent.grant.vST32_025xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "milsOrCITYOrSTATEOrCTRY"
})
@XmlRootElement(name = "RESIDENCE")
public class RESIDENCE {

    @XmlElements({
        @XmlElement(name = "MILS", required = true, type = MILS.class),
        @XmlElement(name = "CITY", required = true, type = CITY.class),
        @XmlElement(name = "STATE", required = true, type = STATE.class),
        @XmlElement(name = "CTRY", required = true, type = CTRY.class)
    })
    protected List<Object> milsOrCITYOrSTATEOrCTRY;

    /**
     * Gets the value of the milsOrCITYOrSTATEOrCTRY property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the milsOrCITYOrSTATEOrCTRY property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMILSOrCITYOrSTATEOrCTRY().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MILS }
     * {@link CITY }
     * {@link STATE }
     * {@link CTRY }
     * 
     * 
     */
    public List<Object> getMILSOrCITYOrSTATEOrCTRY() {
        if (milsOrCITYOrSTATEOrCTRY == null) {
            milsOrCITYOrSTATEOrCTRY = new ArrayList<Object>();
        }
        return this.milsOrCITYOrSTATEOrCTRY;
    }

}
