//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.09 at 05:13:01 PM EST 
//


package xml.us.patent.grant.vST32_025xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "s1VIIIA",
    "s1VIIIB",
    "s1VIIIC"
})
@XmlRootElement(name = "S-1-VIII")
public class S1VIII {

    @XmlElement(name = "S-1-VIII-A", required = true)
    protected S1VIIIA s1VIIIA;
    @XmlElement(name = "S-1-VIII-B", required = true)
    protected S1VIIIB s1VIIIB;
    @XmlElement(name = "S-1-VIII-C", required = true)
    protected S1VIIIC s1VIIIC;

    /**
     * Gets the value of the s1VIIIA property.
     * 
     * @return
     *     possible object is
     *     {@link S1VIIIA }
     *     
     */
    public S1VIIIA getS1VIIIA() {
        return s1VIIIA;
    }

    /**
     * Sets the value of the s1VIIIA property.
     * 
     * @param value
     *     allowed object is
     *     {@link S1VIIIA }
     *     
     */
    public void setS1VIIIA(S1VIIIA value) {
        this.s1VIIIA = value;
    }

    /**
     * Gets the value of the s1VIIIB property.
     * 
     * @return
     *     possible object is
     *     {@link S1VIIIB }
     *     
     */
    public S1VIIIB getS1VIIIB() {
        return s1VIIIB;
    }

    /**
     * Sets the value of the s1VIIIB property.
     * 
     * @param value
     *     allowed object is
     *     {@link S1VIIIB }
     *     
     */
    public void setS1VIIIB(S1VIIIB value) {
        this.s1VIIIB = value;
    }

    /**
     * Gets the value of the s1VIIIC property.
     * 
     * @return
     *     possible object is
     *     {@link S1VIIIC }
     *     
     */
    public S1VIIIC getS1VIIIC() {
        return s1VIIIC;
    }

    /**
     * Sets the value of the s1VIIIC property.
     * 
     * @param value
     *     allowed object is
     *     {@link S1VIIIC }
     *     
     */
    public void setS1VIIIC(S1VIIIC value) {
        this.s1VIIIC = value;
    }

}
