//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.09 at 05:13:01 PM EST 
//


package xml.us.patent.grant.vST32_025xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "s210",
    "s211",
    "s212",
    "s213",
    "s220"
})
@XmlRootElement(name = "S200")
public class S200 {

    @XmlElement(name = "S210", required = true)
    protected S210 s210;
    @XmlElement(name = "S211", required = true)
    protected S211 s211;
    @XmlElement(name = "S212", required = true)
    protected S212 s212;
    @XmlElement(name = "S213", required = true)
    protected S213 s213;
    @XmlElement(name = "S220")
    protected List<S220> s220;

    /**
     * Gets the value of the s210 property.
     * 
     * @return
     *     possible object is
     *     {@link S210 }
     *     
     */
    public S210 getS210() {
        return s210;
    }

    /**
     * Sets the value of the s210 property.
     * 
     * @param value
     *     allowed object is
     *     {@link S210 }
     *     
     */
    public void setS210(S210 value) {
        this.s210 = value;
    }

    /**
     * Gets the value of the s211 property.
     * 
     * @return
     *     possible object is
     *     {@link S211 }
     *     
     */
    public S211 getS211() {
        return s211;
    }

    /**
     * Sets the value of the s211 property.
     * 
     * @param value
     *     allowed object is
     *     {@link S211 }
     *     
     */
    public void setS211(S211 value) {
        this.s211 = value;
    }

    /**
     * Gets the value of the s212 property.
     * 
     * @return
     *     possible object is
     *     {@link S212 }
     *     
     */
    public S212 getS212() {
        return s212;
    }

    /**
     * Sets the value of the s212 property.
     * 
     * @param value
     *     allowed object is
     *     {@link S212 }
     *     
     */
    public void setS212(S212 value) {
        this.s212 = value;
    }

    /**
     * Gets the value of the s213 property.
     * 
     * @return
     *     possible object is
     *     {@link S213 }
     *     
     */
    public S213 getS213() {
        return s213;
    }

    /**
     * Sets the value of the s213 property.
     * 
     * @param value
     *     allowed object is
     *     {@link S213 }
     *     
     */
    public void setS213(S213 value) {
        this.s213 = value;
    }

    /**
     * Gets the value of the s220 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the s220 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getS220().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link S220 }
     * 
     * 
     */
    public List<S220> getS220() {
        if (s220 == null) {
            s220 = new ArrayList<S220>();
        }
        return this.s220;
    }

}
