//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.09 at 05:13:01 PM EST 
//


package xml.us.patent.grant.vST32_025xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "s2IA",
    "s2IB",
    "s2IC",
    "s2ID"
})
@XmlRootElement(name = "S-2-I")
public class S2I {

    @XmlElement(name = "S-2-I-A")
    protected S2IA s2IA;
    @XmlElement(name = "S-2-I-B", required = true)
    protected S2IB s2IB;
    @XmlElement(name = "S-2-I-C")
    protected S2IC s2IC;
    @XmlElement(name = "S-2-I-D", required = true)
    protected S2ID s2ID;

    /**
     * Gets the value of the s2IA property.
     * 
     * @return
     *     possible object is
     *     {@link S2IA }
     *     
     */
    public S2IA getS2IA() {
        return s2IA;
    }

    /**
     * Sets the value of the s2IA property.
     * 
     * @param value
     *     allowed object is
     *     {@link S2IA }
     *     
     */
    public void setS2IA(S2IA value) {
        this.s2IA = value;
    }

    /**
     * Gets the value of the s2IB property.
     * 
     * @return
     *     possible object is
     *     {@link S2IB }
     *     
     */
    public S2IB getS2IB() {
        return s2IB;
    }

    /**
     * Sets the value of the s2IB property.
     * 
     * @param value
     *     allowed object is
     *     {@link S2IB }
     *     
     */
    public void setS2IB(S2IB value) {
        this.s2IB = value;
    }

    /**
     * Gets the value of the s2IC property.
     * 
     * @return
     *     possible object is
     *     {@link S2IC }
     *     
     */
    public S2IC getS2IC() {
        return s2IC;
    }

    /**
     * Sets the value of the s2IC property.
     * 
     * @param value
     *     allowed object is
     *     {@link S2IC }
     *     
     */
    public void setS2IC(S2IC value) {
        this.s2IC = value;
    }

    /**
     * Gets the value of the s2ID property.
     * 
     * @return
     *     possible object is
     *     {@link S2ID }
     *     
     */
    public S2ID getS2ID() {
        return s2ID;
    }

    /**
     * Sets the value of the s2ID property.
     * 
     * @param value
     *     allowed object is
     *     {@link S2ID }
     *     
     */
    public void setS2ID(S2ID value) {
        this.s2ID = value;
    }

}
