//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.09 at 05:13:01 PM EST 
//


package xml.us.patent.grant.vST32_025xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "s301",
    "s302",
    "s303",
    "s304",
    "s305",
    "s306",
    "s307",
    "s308",
    "s309",
    "s310",
    "s311",
    "s313"
})
@XmlRootElement(name = "S300")
public class S300 {

    @XmlElement(name = "S301")
    protected S301 s301;
    @XmlElement(name = "S302")
    protected S302 s302;
    @XmlElement(name = "S303")
    protected S303 s303;
    @XmlElement(name = "S304")
    protected S304 s304;
    @XmlElement(name = "S305")
    protected S305 s305;
    @XmlElement(name = "S306")
    protected S306 s306;
    @XmlElement(name = "S307")
    protected S307 s307;
    @XmlElement(name = "S308")
    protected S308 s308;
    @XmlElement(name = "S309")
    protected S309 s309;
    @XmlElement(name = "S310")
    protected S310 s310;
    @XmlElement(name = "S311")
    protected S311 s311;
    @XmlElement(name = "S313")
    protected S313 s313;

    /**
     * Gets the value of the s301 property.
     * 
     * @return
     *     possible object is
     *     {@link S301 }
     *     
     */
    public S301 getS301() {
        return s301;
    }

    /**
     * Sets the value of the s301 property.
     * 
     * @param value
     *     allowed object is
     *     {@link S301 }
     *     
     */
    public void setS301(S301 value) {
        this.s301 = value;
    }

    /**
     * Gets the value of the s302 property.
     * 
     * @return
     *     possible object is
     *     {@link S302 }
     *     
     */
    public S302 getS302() {
        return s302;
    }

    /**
     * Sets the value of the s302 property.
     * 
     * @param value
     *     allowed object is
     *     {@link S302 }
     *     
     */
    public void setS302(S302 value) {
        this.s302 = value;
    }

    /**
     * Gets the value of the s303 property.
     * 
     * @return
     *     possible object is
     *     {@link S303 }
     *     
     */
    public S303 getS303() {
        return s303;
    }

    /**
     * Sets the value of the s303 property.
     * 
     * @param value
     *     allowed object is
     *     {@link S303 }
     *     
     */
    public void setS303(S303 value) {
        this.s303 = value;
    }

    /**
     * Gets the value of the s304 property.
     * 
     * @return
     *     possible object is
     *     {@link S304 }
     *     
     */
    public S304 getS304() {
        return s304;
    }

    /**
     * Sets the value of the s304 property.
     * 
     * @param value
     *     allowed object is
     *     {@link S304 }
     *     
     */
    public void setS304(S304 value) {
        this.s304 = value;
    }

    /**
     * Gets the value of the s305 property.
     * 
     * @return
     *     possible object is
     *     {@link S305 }
     *     
     */
    public S305 getS305() {
        return s305;
    }

    /**
     * Sets the value of the s305 property.
     * 
     * @param value
     *     allowed object is
     *     {@link S305 }
     *     
     */
    public void setS305(S305 value) {
        this.s305 = value;
    }

    /**
     * Gets the value of the s306 property.
     * 
     * @return
     *     possible object is
     *     {@link S306 }
     *     
     */
    public S306 getS306() {
        return s306;
    }

    /**
     * Sets the value of the s306 property.
     * 
     * @param value
     *     allowed object is
     *     {@link S306 }
     *     
     */
    public void setS306(S306 value) {
        this.s306 = value;
    }

    /**
     * Gets the value of the s307 property.
     * 
     * @return
     *     possible object is
     *     {@link S307 }
     *     
     */
    public S307 getS307() {
        return s307;
    }

    /**
     * Sets the value of the s307 property.
     * 
     * @param value
     *     allowed object is
     *     {@link S307 }
     *     
     */
    public void setS307(S307 value) {
        this.s307 = value;
    }

    /**
     * Gets the value of the s308 property.
     * 
     * @return
     *     possible object is
     *     {@link S308 }
     *     
     */
    public S308 getS308() {
        return s308;
    }

    /**
     * Sets the value of the s308 property.
     * 
     * @param value
     *     allowed object is
     *     {@link S308 }
     *     
     */
    public void setS308(S308 value) {
        this.s308 = value;
    }

    /**
     * Gets the value of the s309 property.
     * 
     * @return
     *     possible object is
     *     {@link S309 }
     *     
     */
    public S309 getS309() {
        return s309;
    }

    /**
     * Sets the value of the s309 property.
     * 
     * @param value
     *     allowed object is
     *     {@link S309 }
     *     
     */
    public void setS309(S309 value) {
        this.s309 = value;
    }

    /**
     * Gets the value of the s310 property.
     * 
     * @return
     *     possible object is
     *     {@link S310 }
     *     
     */
    public S310 getS310() {
        return s310;
    }

    /**
     * Sets the value of the s310 property.
     * 
     * @param value
     *     allowed object is
     *     {@link S310 }
     *     
     */
    public void setS310(S310 value) {
        this.s310 = value;
    }

    /**
     * Gets the value of the s311 property.
     * 
     * @return
     *     possible object is
     *     {@link S311 }
     *     
     */
    public S311 getS311() {
        return s311;
    }

    /**
     * Sets the value of the s311 property.
     * 
     * @param value
     *     allowed object is
     *     {@link S311 }
     *     
     */
    public void setS311(S311 value) {
        this.s311 = value;
    }

    /**
     * Gets the value of the s313 property.
     * 
     * @return
     *     possible object is
     *     {@link S313 }
     *     
     */
    public S313 getS313() {
        return s313;
    }

    /**
     * Sets the value of the s313 property.
     * 
     * @param value
     *     allowed object is
     *     {@link S313 }
     *     
     */
    public void setS313(S313 value) {
        this.s313 = value;
    }

}
