//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.09 at 05:13:01 PM EST 
//


package xml.us.patent.grant.vST32_025xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "seqlstoldOrSEQLSTNEWOrTable"
})
@XmlRootElement(name = "SEQLST-US")
public class SEQLSTUS {

    @XmlAttribute(name = "ID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    @XmlElements({
        @XmlElement(name = "SEQ-LST-OLD", required = true, type = SEQLSTOLD.class),
        @XmlElement(name = "SEQ-LST-NEW", required = true, type = SEQLSTNEW.class),
        @XmlElement(name = "table", required = true, type = Table.class)
    })
    protected List<Object> seqlstoldOrSEQLSTNEWOrTable;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the seqlstoldOrSEQLSTNEWOrTable property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the seqlstoldOrSEQLSTNEWOrTable property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSEQLSTOLDOrSEQLSTNEWOrTable().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SEQLSTOLD }
     * {@link SEQLSTNEW }
     * {@link Table }
     * 
     * 
     */
    public List<Object> getSEQLSTOLDOrSEQLSTNEWOrTable() {
        if (seqlstoldOrSEQLSTNEWOrTable == null) {
            seqlstoldOrSEQLSTNEWOrTable = new ArrayList<Object>();
        }
        return this.seqlstoldOrSEQLSTNEWOrTable;
    }

}
